import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createMemoryCardExporter} from '../web/event-room/memory-card.js';
import {memoryCardMarkup} from '../web/event-room/memory-card-view.js';
const defer=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve:v=>resolve(v)};};
function setup(overrides={}){const user={id:'me',name:'QA author',avatar:{hair:1}},room={id:'show',title:'QA show',venue:'QA venue'},photos=[{id:'mine',ownerId:'me',roomId:'show',revision:1},{id:'peer',ownerId:'other',roomId:'show',revision:1}];let state={connection:'connected',identity:{status:'ready',user},recap:{actorId:'me',room,loaded:true,photos:{items:photos}}};const calls=[];const exporter=createMemoryCardExporter({getState:()=>state,refresh:async()=>calls.push('refresh'),fetchPhotoBlob:async id=>{calls.push(id);return new Blob(['qa']);},render:async data=>{calls.push(data);return new Blob(['png']);},save:async()=>calls.push('save'),...overrides});return {exporter,calls,get:()=>state,set:s=>state=s,selection:{photoIds:['mine'],includeAvatar:true,consent:true}};}
test('explicit own-photo card preserves attribution and rechecks after rendering without sharing mutations',async()=>{const h=setup();assert.deepEqual(await h.exporter.run(h.selection),{downloaded:true});assert.equal(h.calls.filter(x=>x==='refresh').length,2);assert.equal(h.calls.at(-1),'save');const rendered=h.calls.find(x=>x?.photos);assert.equal(rendered.photos[0].authorName,'QA author');assert.equal(rendered.author.avatar.hair,1);});
test('peer photos, missing consent, stale recap, foreign actor and offline state cannot export',async()=>{for(const kind of ['peer','consent','stale','actor','offline']){const h=setup();if(kind==='peer')h.selection.photoIds=['peer'];if(kind==='consent')h.selection.consent=false;if(kind==='stale')h.get().recap.stale=true;if(kind==='actor')h.get().recap.actorId='other';if(kind==='offline')h.get().connection='offline';await assert.rejects(h.exporter.run(h.selection));assert.deepEqual(h.calls,[]);}});
test('zero photos yields a private text ticket, no photo reads',async()=>{const h=setup();await h.exporter.run({...h.selection,photoIds:[],includeAvatar:false});assert.ok(!h.calls.includes('mine'));assert.equal(h.calls.find(x=>x?.photos).author.avatar,null);});
test('duplicate click does not begin another export; cancellation prevents a late download',async()=>{const gate=defer(),h=setup({render:()=>gate.promise});const pending=h.exporter.run(h.selection);await new Promise(r=>setImmediate(r));assert.deepEqual(await h.exporter.run(h.selection),{busy:true});assert.equal(h.exporter.cancel(),true);gate.resolve(new Blob(['late']));assert.deepEqual(await pending,{cancelled:true});assert.ok(!h.calls.includes('save'));});
test('second-tab deletion and saved avatar changes during render require a new review',async()=>{for(const change of ['photo','avatar','identity','room']){const gate=defer(),h=setup({render:()=>gate.promise});const pending=h.exporter.run(h.selection);await new Promise(r=>setImmediate(r));if(change==='photo')h.get().recap.photos.items=[];if(change==='avatar')h.get().identity.user.avatar.hair=2;if(change==='identity')h.get().identity.user.id='other';if(change==='room')h.get().recap.room.id='next';gate.resolve(new Blob(['late']));await assert.rejects(pending,e=>e.code==='MEMORY_REVIEW_CHANGED');assert.ok(!h.calls.includes('save'));}});
test('failed read remains retryable and cannot download partial photos',async()=>{let offline=true;const h=setup({fetchPhotoBlob:async()=>{if(offline)throw Error('offline');return new Blob(['qa']);}});await assert.rejects(h.exporter.run(h.selection));assert.ok(!h.calls.includes('save'));offline=false;await h.exporter.run(h.selection);assert.equal(h.calls.at(-1),'save');});
test('selection is copied and current-page markup excludes private peers and escapes names',async()=>{const h=setup(),gate=defer();const exporter=createMemoryCardExporter({getState:h.get,refresh:()=>gate.promise,fetchPhotoBlob:async()=>new Blob(['qa']),render:async()=>new Blob(['qa']),save:()=>{}});const pending=exporter.run(h.selection);h.selection.photoIds.push('peer');gate.resolve();assert.deepEqual(await pending,{downloaded:true});const html=memoryCardMarkup({recap:h.get().recap,user:{...h.get().identity.user,name:'<script>'}});assert.ok(!html.includes('value="peer"'));assert.match(html,/&lt;script&gt;/);assert.match(html,/文字纪念票/);});
