import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {participationFixture} from './helpers/participation-fixture.js';
import {photoData} from './event-contract.test.js';
for(const engine of ['Node','Worker']){
 test(`${engine} participation: default quiet survives restart and exposes no real location or identity`,async t=>{const f=await participationFixture(t,engine),{a,b,room}=await f.two();let roster=await f.roster(room,a);assert.equal(roster.members.length,2);for(const m of roster.members){assert.equal(m.participation,'quiet');assert.equal(m.participationRevision,1);assert.deepEqual(Object.keys(m).sort(),['avatar','id','joinedAt','name','participation','participationRevision'].sort());}assert.equal((await f.send(room,a,b)).body.error.code,'PARTICIPATION_QUIET');await f.restart();assert.equal((await f.roster(room,b)).members.find(m=>m.id===a.user.id).participation,'quiet');});
 test(`${engine} participation: only a current member can change their own validated room choice`,async t=>{const f=await participationFixture(t,engine),{a,b,room}=await f.two(),outside=await f.session('合成未入场');assert.equal((await f.choice(room,outside,'open')).status,404);assert.equal((await f.choice(room,a,'invalid')).status,400);assert.equal((await f.choice(room,a,'open',0)).status,400);assert.equal((await f.request(`/rooms/${room.id}/participation`,{method:'PATCH',token:a.token,data:{mode:'open',revision:1,userId:b.user.id}})).status,400);assert.equal((await f.request(`/rooms/${room.id}/participation`,{method:'PATCH',data:{mode:'open',revision:1}})).status,401);const other=await f.room(a,'open');assert.equal((await f.roster(room,a)).members.find(m=>m.id===a.user.id).participation,'quiet');assert.equal((await f.roster(other,a)).members[0].participation,'open');});
 test(`${engine} participation: both choices are required; duplicate and competing revisions commit once`,async t=>{const f=await participationFixture(t,engine),{a,b,room}=await f.two(),key=randomUUID();const first=await f.choice(room,a,'open',1,key),repeat=await f.choice(room,a,'open',1,key);assert.equal(first.status,200);assert.deepEqual(repeat.body,first.body);assert.equal(repeat.headers.get('Idempotency-Replayed'),'true');assert.equal((await f.send(room,a,b)).status,409);const race=await Promise.all([f.choice(room,b,'open',1),f.choice(room,b,'quiet',1)]);assert.equal(race.filter(r=>r.status===200).length,1);assert.equal(race.filter(r=>r.status===409).length,1);const own=(await f.roster(room,b)).members.find(m=>m.id===b.user.id);if(own.participation==='quiet')await f.choice(room,b,'open',own.participationRevision);assert.equal((await f.send(room,a,b)).status,201);});
 test(`${engine} participation: quiet atomically cancels pending greetings without granting photos or friendship`,async t=>{const f=await participationFixture(t,engine),{a,b,room}=await f.two();await f.choice(room,a,'open');await f.choice(room,b,'open');const greeting=(await f.send(room,a,b)).body.greeting;const change=await f.choice(room,b,'quiet',2);assert.equal(change.status,200);const social=(await f.request('/social',{token:a.token})).body;assert.deepEqual(social.outgoing,[]);assert.deepEqual(social.friends,[]);const accept=await f.request(`/greetings/${greeting.id}/accept`,{method:'POST',token:b.token,data:{revision:greeting.revision}});assert.equal(accept.status,409);await f.choice(room,b,'open',3);assert.equal((await f.request('/social',{token:b.token})).body.incoming.length,0);});
 test(`${engine} participation: quiet preserves existing friends, text chat and photo boundaries`,async t=>{const f=await participationFixture(t,engine),{a,b,room}=await f.two();await f.choice(room,a,'open');await f.choice(room,b,'open');const g=(await f.send(room,a,b)).body.greeting;assert.equal((await f.request(`/greetings/${g.id}/accept`,{method:'POST',token:b.token,data:{revision:g.revision}})).status,200);await f.choice(room,a,'quiet',2);const photos=[];for(const visibility of ['private','members'])photos.push((await f.request(`/rooms/${room.id}/photos`,{method:'POST',token:a.token,data:{...photoData(),visibility}})).body.photo);assert.equal((await f.request(`/photos/${photos[0].id}/image`,{token:b.token})).status,404);assert.equal((await f.request(`/photos/${photos[1].id}/image`,{token:b.token})).status,200);assert.equal((await f.request('/social',{token:b.token})).body.friends[0].userId,a.user.id);assert.equal((await f.request(`/chats/${a.user.id}/messages`,{method:'POST',token:b.token,data:{text:'合成：刚才这张照片让我想起那首歌。'}})).status,201);await f.request(`/rooms/${room.id}/leave`,{method:'POST',token:a.token,data:{}});assert.equal((await f.choice(room,a,'open',3)).status,404);assert.equal((await f.request(`/photos/${photos[1].id}/image`,{token:b.token})).status,404);});
 test(`${engine} participation: returning quietly ends a previous pending greeting and never re-shares a photo`,async t=>{const f=await participationFixture(t,engine),{a,b,room}=await f.two();await f.choice(room,a,'open');await f.choice(room,b,'open');await f.send(room,a,b);const p=(await f.request(`/rooms/${room.id}/photos`,{method:'POST',token:a.token,data:{...photoData(),visibility:'members'}})).body.photo;await f.request(`/rooms/${room.id}/leave`,{method:'POST',token:a.token,data:{}});await f.join(room,a);assert.equal((await f.roster(room,a)).members.find(m=>m.id===a.user.id).participation,'quiet');assert.deepEqual((await f.request('/social',{token:b.token})).body.incoming,[]);assert.equal((await f.request(`/photos/${p.id}/image`,{token:b.token})).status,404);});
}
test('Worker participation: quiet wins against a greeting planned before its transaction',async t=>{const f=await participationFixture(t,'Worker'),{a,b,room}=await f.two();await f.choice(room,a,'open');await f.choice(room,b,'open');const original=f.env.DB.batch.bind(f.env.DB);let release,entered;const gate=new Promise(r=>release=r),seen=new Promise(r=>entered=r);f.env.DB.batch=async rows=>{if(rows.some(r=>r.query.includes('INSERT INTO event_social_pairs'))){entered();await gate;}return original(rows);};const sending=f.send(room,a,b);await seen;await f.choice(room,b,'quiet',2);release();assert.equal((await sending).status,409);const s=(await f.request('/social',{token:b.token})).body;assert.deepEqual(s.incoming,[]);assert.deepEqual(s.friends,[]);});
