import {randomUUID} from 'node:crypto';
import {socialAllowedSQL} from './event-social.js';
import {spaceWriteGuard} from './space-access.js';
import {MUSIC_CATALOGUE,musicReference} from './music-catalogue.js';
import {WORLDCUP_ALBUMS} from './worldcup-albums.js';
import {conversationGuard,combineGuards,musicText,customEntries} from './music-play-access.js';
const UUID='[0-9a-f-]{36}';
/** Voluntary text-only play. Secret choices are never returned before reveal. */
export async function handleEventGames(c){
 const {request,path,method,user,get,stmt,db,fail,json,readJSON,keys,revision,mutate,replayOperation,now,rate}=c;
 const collection=new RegExp(`^/(rooms|communities)/(${UUID})/games$`).exec(path),route=new RegExp(`^/games/(${UUID})(?:/(join|leave|start|answer|reveal|next|skip|cancel))?$`).exec(path);if(!collection&&!route)return null;
 const game=route?await get('SELECT * FROM event_games WHERE id=?',route[1]):null;if(route&&!game)fail(404,'GAME_UNAVAILABLE','找不到这局小游戏。');
 const kind=collection?(collection[1]==='rooms'?'room':'community'):game.kind,scope=collection?.[2]||game.scope_id,membership=conversationGuard(kind,scope,user.id);
 const access=game?combineGuards(membership,{sql:socialAllowedSQL('?','?'),args:[user.id,game.creator_id,game.creator_id,user.id]}):membership;
 const allowed=async g=>Boolean(await get(`SELECT 1 ok WHERE ${g.sql}`,...g.args));if(!await allowed(access))fail(403,'GAME_MEMBERSHIP_REQUIRED','请本人明确加入聊天室；退出、移除或屏蔽后不能读取或参与。');
 const input=method==='POST'?await readJSON(request):null;if(input){const receipt=await replayOperation(input);if(receipt)return receipt;}
 const parent=await get(`SELECT host_id FROM ${kind==='room'?'event_rooms':'event_communities'} WHERE id=?`,scope),host=game&&(game.creator_id===user.id||parent?.host_id===user.id);
 const rows=async(sql,...args)=>(await stmt(sql,...args).all()).results;
 const gameView=r=>({id:r.id,type:r.type,title:r.title,creatorId:r.creator_id,creatorName:r.creator_name,phase:r.phase,revision:r.revision,roundLimit:r.round_limit,createdAt:r.created_at,finishReason:r.finish_reason});
 // Each person's current conversation membership remains authoritative.
 const eligibleSQL=`p.left_at IS NULL AND ${conversationGuard(kind,scope,'p.user_id').sql}`;
 const eligibleArgs=conversationGuard(kind,scope,'p.user_id').args;
 // The guard helper binds user IDs; substitute only this trusted SQL expression.
 const stamps=game?{sql:`${socialAllowedSQL('p.user_id','?')} AND COALESCE((SELECT revision FROM event_social_blocks WHERE actor_id=p.user_id AND target_id=?),0)=p.player_block_revision AND COALESCE((SELECT revision FROM event_social_blocks WHERE actor_id=? AND target_id=p.user_id),0)=p.creator_block_revision`,args:[game.creator_id,game.creator_id,game.creator_id,game.creator_id]}:{sql:'1=1',args:[]};
 const eligible={sql:`(${eligibleSQL.replaceAll('user_id=?','user_id=p.user_id')}) AND (${stamps.sql})`,args:[...eligibleArgs.filter(v=>v!=='p.user_id'),...stamps.args]};
 const players=async()=>rows(`SELECT p.*,u.name,u.avatar FROM event_game_players p JOIN avatar_users u ON u.id=p.user_id WHERE p.game_id=? AND ${eligible.sql} ORDER BY p.joined_at,p.user_id`,game.id,...eligible.args);
 const round=async()=>get('SELECT * FROM event_game_rounds WHERE game_id=? ORDER BY ordinal DESC LIMIT 1',game.id);
 const activeParticipant={sql:`EXISTS(SELECT 1 FROM event_game_players p WHERE game_id=? AND user_id=? AND ${eligible.sql})`,args:[game?.id,user.id,...eligible.args]};
 const withRevision=(writable,expected)=>combineGuards(access,writable,{sql:'EXISTS(SELECT 1 FROM event_games WHERE id=? AND revision=? AND phase=?)',args:[game.id,expected,game.phase]});
 if(collection&&method==='GET'){const before=new URL(request.url).searchParams.get('before');if(before&&!new RegExp('^'+UUID+'$').test(before))fail(400,'INVALID_CURSOR','分页位置无效。');if(before&&!await get(`SELECT id FROM event_games WHERE id=? AND kind=? AND scope_id=? AND ${socialAllowedSQL('?','creator_id')}`,before,kind,scope,user.id,user.id))fail(400,'INVALID_CURSOR','分页位置当前不可见。');const q=before?' AND (created_at<(SELECT created_at FROM event_games WHERE id=?) OR (created_at=(SELECT created_at FROM event_games WHERE id=?) AND id<?))':'',result=await db.batch([stmt(`SELECT 1 ok WHERE ${access.sql}`,...access.args),stmt(`SELECT * FROM event_games WHERE kind=? AND scope_id=? AND ${socialAllowedSQL('?','creator_id')}${q} ORDER BY created_at DESC,id DESC LIMIT 21`,kind,scope,user.id,user.id,...(before?[before,before,before]:[])),stmt(kind==='community'?'SELECT archived_at FROM event_communities WHERE id=?':'SELECT NULL archived_at',...(kind==='community'?[scope]:[]))]);if(!result[0].results.length)fail(403,'GAME_MEMBERSHIP_REQUIRED','读取时资格已经变化。');return json(200,{actorId:user.id,archived:Boolean(result[2].results[0]?.archived_at),games:result[1].results.slice(0,20).map(gameView),nextCursor:result[1].results.length>20?result[1].results[19].id:null});}
 if(collection&&method==='POST'){
  const d=input;keys(d,['type','title','entries','seedRecordingId','seedTitle','seedArtist','roundLimit','createConsent']);if(d.createConsent!==true)fail(400,'GAME_CONSENT_REQUIRED','请明确发起文字小游戏；成员自己决定是否参与。');if(!['preference','relay'].includes(d.type))fail(400,'INVALID_GAME','请选择默契局或音乐关系接龙。');const title=musicText(fail,d.title,40,true),limit=d.roundLimit;if(!Number.isInteger(limit)||limit<1||limit>(d.type==='preference'?3:6))fail(400,'INVALID_ROUNDS','默契局最多三轮，接龙最多六步。');
  let options;if(d.type==='preference'){if(d.seedRecordingId!==undefined||d.seedTitle!==undefined||d.seedArtist!==undefined)fail(400,'INVALID_GAME_SEED','默契局不使用接龙起点。');options={entries:d.entries===undefined?WORLDCUP_ALBUMS:customEntries(fail,d.entries)};}else{if(d.entries!==undefined)fail(400,'INVALID_GAME_ENTRIES','接龙不使用默契局选项。');const seed=musicReference(d.seedRecordingId);if(d.seedRecordingId!==undefined&&!seed)fail(400,'INVALID_RECORDING','只接受已留档关系卡的编号。');if(seed&&(d.seedTitle!==undefined||d.seedArtist!==undefined))fail(400,'INVALID_GAME_SEED','已核实起点不能混入自填资料。');options={seed:seed?{recordingId:seed.id,title:seed.title,artist:seed.artists.join(' / '),provenance:'verified-catalogue'}:{recordingId:null,title:musicText(fail,d.seedTitle,80,true),artist:musicText(fail,d.seedArtist??'',80),provenance:'member-text'}};}
  const writable=await spaceWriteGuard(get,fail,kind,scope);return mutate(d,async()=>{await rate('music-game:'+user.id,5,86400000);const id=randomUUID();return{status:201,body:{actorId:user.id,gameId:id},guard:combineGuards(access,writable),statements:[stmt('INSERT INTO event_games(id,kind,scope_id,creator_id,creator_name,type,title,options_json,round_limit,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',id,kind,scope,user.id,user.name,d.type,title,JSON.stringify(options),limit,now(),now()),stmt('INSERT INTO event_game_players(game_id,user_id,joined_at) VALUES(?,?,?)',id,user.id,now())]};});
 }
 if(method==='GET'&&!route[2]){
  const snapshot=await db.batch([stmt(`SELECT 1 ok WHERE ${access.sql}`,...access.args),stmt(`SELECT p.user_id,p.revision,p.joined_at,u.name,u.avatar FROM event_game_players p JOIN avatar_users u ON u.id=p.user_id WHERE p.game_id=? AND ${eligible.sql} AND ${socialAllowedSQL('?','p.user_id')} ORDER BY p.joined_at,p.user_id`,game.id,...eligible.args,user.id,user.id),stmt('SELECT * FROM event_game_rounds WHERE game_id=? ORDER BY ordinal',game.id),stmt(`SELECT a.*,${socialAllowedSQL('?','a.user_id')} visible FROM event_game_answers a WHERE game_id=? ORDER BY ordinal,a.created_at,a.user_id`,user.id,user.id,game.id),stmt(`SELECT p.user_id FROM event_game_players p WHERE game_id=? AND ${eligible.sql}`,game.id,...eligible.args),stmt(`SELECT p.*,(${eligible.sql}) eligible FROM event_game_players p WHERE game_id=? AND user_id=?`,...eligible.args,game.id,user.id),stmt(kind==='community'?'SELECT archived_at FROM event_communities WHERE id=?':'SELECT NULL archived_at',...(kind==='community'?[scope]:[]))]);
  if(!snapshot[0].results.length)fail(403,'GAME_MEMBERSHIP_REQUIRED','读取时资格已经变化。');const eligibleIds=new Set(snapshot[4].results.map(p=>p.user_id)),visiblePlayers=snapshot[1].results,visibleIds=new Set(visiblePlayers.map(p=>p.user_id)),my=snapshot[5].results[0],options=JSON.parse(game.options_json);
  const rounds=snapshot[2].results.map(r=>{const answers=snapshot[3].results.filter(a=>a.ordinal===r.ordinal),own=answers.find(a=>a.user_id===user.id&&(r.status!=='open'||eligibleIds.has(a.user_id))),out={ordinal:r.ordinal,status:r.status,revision:r.revision,reason:r.reason,turnId:visibleIds.has(r.turn_user_id)?r.turn_user_id:null,isMyTurn:r.turn_user_id===user.id,answeredCount:r.status==='open'?answers.filter(a=>eligibleIds.has(a.user_id)).length:answers.length,myAnswer:own?JSON.parse(own.payload_json):null};if(r.status==='revealed'){if(game.type==='preference'){const counts=new Map();for(const a of answers){const id=JSON.parse(a.payload_json).choiceId;counts.set(id,(counts.get(id)||0)+1);}out.result=options.entries.map(e=>({entry:e,count:counts.get(e.id)||0}));out.commonChoices=out.result.filter(e=>e.count>=2).map(e=>e.entry.id);}else{const a=answers[0];out.step=a?(a.visible?{...JSON.parse(a.payload_json),authorName:a.author_name,authorId:a.user_id}:{unavailable:true}):null;}}return out;});
  return json(200,{actorId:user.id,game:gameView(game),host,options,players:visiblePlayers.map(p=>({id:p.user_id,name:p.name,avatar:p.avatar,revision:p.revision})),archived:Boolean(snapshot[6].results[0]?.archived_at),joined:Boolean(my&&!my.left_at&&my.eligible),canLeave:Boolean(my&&!my.left_at),playerRevision:my?.revision||null,rounds,catalogue:game.type==='relay'?MUSIC_CATALOGUE:undefined});
 }
 if(method!=='POST'||!route[2])return null;
 const d=input,action=route[2],writable=action==='leave'||action==='cancel'?{sql:'1=1',args:[]}:await spaceWriteGuard(get,fail,kind,scope);
 if(action==='join'){
  keys(d,['revision','joinConsent']);if(d.joinConsent!==true)fail(400,'GAME_CONSENT_REQUIRED','请本人明确参与这局；不自动变更联系意愿或成为朋友。');return mutate(d,async()=>{revision(game,d.revision);if(game.phase!=='waiting')fail(409,'GAME_STARTED','本局已开始，下一局再自愿加入。');const roster=await players();if(roster.length>=8&&!roster.some(p=>p.user_id===user.id))fail(409,'GAME_FULL','一局最多八人。');const guard=combineGuards(withRevision(writable,d.revision),{sql:'(SELECT COUNT(*) FROM event_game_players p WHERE game_id=? AND '+eligible.sql+')<8 OR EXISTS(SELECT 1 FROM event_game_players WHERE game_id=? AND user_id=? AND left_at IS NULL)',args:[game.id,...eligible.args,game.id,user.id]});return{body:{actorId:user.id,joined:true},guard,statements:[stmt('INSERT INTO event_game_players(game_id,user_id,joined_at,player_block_revision,creator_block_revision) VALUES(?,?,?,COALESCE((SELECT revision FROM event_social_blocks WHERE actor_id=? AND target_id=?),0),COALESCE((SELECT revision FROM event_social_blocks WHERE actor_id=? AND target_id=?),0)) ON CONFLICT(game_id,user_id) DO UPDATE SET left_at=NULL,joined_at=excluded.joined_at,player_block_revision=excluded.player_block_revision,creator_block_revision=excluded.creator_block_revision,revision=revision+1',game.id,user.id,now(),user.id,game.creator_id,game.creator_id,user.id),stmt('UPDATE event_games SET revision=revision+1,updated_at=? WHERE id=?',now(),game.id)]};});
 }
 if(action==='leave'){
  keys(d,['playerRevision']);const p=await get('SELECT * FROM event_game_players WHERE game_id=? AND user_id=?',game.id,user.id);if(!p||p.left_at)fail(409,'GAME_NOT_JOINED','你已不在这局中。');return mutate(d,async()=>{revision(p,d.playerRevision);const guard=combineGuards(access,{sql:'EXISTS(SELECT 1 FROM event_game_players WHERE game_id=? AND user_id=? AND revision=? AND left_at IS NULL)',args:[game.id,user.id,d.playerRevision]});return{body:{actorId:user.id,left:true},guard,statements:[stmt('UPDATE event_game_players SET left_at=?,revision=revision+1 WHERE game_id=? AND user_id=?',now(),game.id,user.id),stmt("DELETE FROM event_game_answers WHERE game_id=? AND user_id=? AND ordinal IN(SELECT ordinal FROM event_game_rounds WHERE game_id=? AND status='open')",game.id,user.id,game.id),stmt("UPDATE event_games SET revision=revision+1,updated_at=?,phase=CASE WHEN phase='playing' AND (SELECT COUNT(*) FROM event_game_players p WHERE game_id=? AND "+eligible.sql+")<2 THEN 'cancelled' ELSE phase END,finish_reason=CASE WHEN phase='playing' AND (SELECT COUNT(*) FROM event_game_players p WHERE game_id=? AND "+eligible.sql+")<2 THEN 'fewer-than-two' ELSE finish_reason END WHERE id=?",now(),game.id,...eligible.args,game.id,...eligible.args,game.id)]};});
 }
 if(action==='start'){
  keys(d,['revision','startConsent']);if(!host||d.startConsent!==true)fail(403,'GAME_HOST_REQUIRED','发起者或主办方明确确认后开始。');return mutate(d,async()=>{revision(game,d.revision);if(game.phase!=='waiting')fail(409,'GAME_STARTED','本局已开始或结束。');const roster=await players();if(roster.length<2)fail(409,'TWO_PLAYERS_REQUIRED','至少两位本人自愿加入后才能开始。');const guard=combineGuards(withRevision(writable,d.revision),{sql:'(SELECT COUNT(*) FROM event_game_players p WHERE game_id=? AND '+eligible.sql+')>=2',args:[game.id,...eligible.args]});return{body:{actorId:user.id,started:true},guard,statements:[stmt("UPDATE event_games SET phase='playing',revision=revision+1,updated_at=? WHERE id=?",now(),game.id),stmt('INSERT INTO event_game_rounds(game_id,ordinal,turn_user_id) VALUES(?,1,?)',game.id,game.type==='relay'?roster[0].user_id:null)]};});
 }
 if(action==='cancel'){
  keys(d,['revision','cancelConsent']);if(!host||d.cancelConsent!==true)fail(403,'GAME_HOST_REQUIRED','发起者或主办方明确确认后结束这局。');return mutate(d,async()=>{revision(game,d.revision);if(['completed','cancelled'].includes(game.phase))fail(409,'GAME_ENDED','本局已经结束。');return{body:{actorId:user.id,cancelled:true},guard:withRevision(writable,d.revision),statements:[stmt("UPDATE event_games SET phase='cancelled',finish_reason='host-cancelled',revision=revision+1,updated_at=? WHERE id=?",now(),game.id),stmt("DELETE FROM event_game_answers WHERE game_id=? AND ordinal IN(SELECT ordinal FROM event_game_rounds WHERE game_id=? AND status='open')",game.id,game.id)]};});
 }
 const current=await round();if(game.phase!=='playing'||!current)fail(409,'GAME_NOT_PLAYING','本局不在进行中。');
 const roundGuard=()=>combineGuards(withRevision(writable,game.revision),{sql:'EXISTS(SELECT 1 FROM event_game_rounds WHERE game_id=? AND ordinal=? AND revision=? AND status=?)',args:[game.id,current.ordinal,d.revision,current.status]});
 if(action==='answer'){
  keys(d,['revision','choiceId','recordingId','title','artist','reason','answerConsent']);if(d.answerConsent!==true)fail(400,'ANSWER_CONSENT_REQUIRED','请明确提交本轮选择或接龙文字。');if(!await allowed(activeParticipant))fail(403,'GAME_NOT_JOINED','请先本人加入这局。');let payload,sourceGuard={sql:'1=1',args:[]};
  if(game.type==='preference'){if(!JSON.parse(game.options_json).entries.some(e=>e.id===d.choiceId)||['recordingId','title','artist','reason'].some(k=>d[k]!==undefined))fail(400,'INVALID_CHOICE','请只选择本局的一个选项。');payload={choiceId:d.choiceId};}
  else{if(current.turn_user_id!==user.id)fail(409,'OTHER_PLAYER_TURN','等待当前轮到的参与者，不替别人接龙。');if(d.choiceId!==undefined)fail(400,'INVALID_STEP','接龙不使用默契选项。');const previous=await get("SELECT a.*,u.name FROM event_game_answers a JOIN avatar_users u ON u.id=a.user_id JOIN event_game_rounds r ON r.game_id=a.game_id AND r.ordinal=a.ordinal WHERE a.game_id=? AND r.status='revealed' ORDER BY a.ordinal DESC LIMIT 1",game.id),prior=previous?JSON.parse(previous.payload_json):JSON.parse(game.options_json).seed;if(previous)sourceGuard={sql:socialAllowedSQL('?','?'),args:[user.id,previous.user_id,previous.user_id,user.id]};if(previous&&!await allowed(sourceGuard))fail(404,'PREVIOUS_STEP_UNAVAILABLE','上一段目前不可见；不能绕过屏蔽继续引用。');const recording=musicReference(d.recordingId),reason=musicText(fail,d.reason||'',200,true);
   if(d.recordingId!==undefined){if(!recording||d.title!==undefined||d.artist!==undefined)fail(400,'INVALID_STEP','核实关系只使用已留档歌曲编号。');const before=musicReference(prior.recordingId),shared=before?.artistIds.filter(id=>recording.artistIds.includes(id))||[];if(!shared.length||before.id===recording.id)fail(400,'RELATION_NOT_VERIFIED','这两张关系卡没有已核实的共同音乐人，请改用明确自述的关联理由。');const used=await rows('SELECT payload_json FROM event_game_answers WHERE game_id=?',game.id);if(prior.recordingId===recording.id||used.some(a=>JSON.parse(a.payload_json).recordingId===recording.id)||JSON.parse(game.options_json).seed.recordingId===recording.id)fail(409,'RECORDING_ALREADY_USED','这张关系卡已在本局出现，换一张或自述新的关联。');payload={recordingId:recording.id,title:recording.title,artist:recording.artists.join(' / '),reason,provenance:'verified-catalogue',sharedArtistIds:shared};}
   else payload={recordingId:null,title:musicText(fail,d.title,80,true),artist:musicText(fail,d.artist||'',80),reason,provenance:'member-text'};
  }
  return mutate(d,async()=>{revision(current,d.revision);if(current.status!=='open')fail(409,'ROUND_REVEALED','本轮已结束，不再提交。');if(await get('SELECT 1 FROM event_game_answers WHERE game_id=? AND ordinal=? AND user_id=?',game.id,current.ordinal,user.id))fail(409,'ALREADY_ANSWERED','本轮已经提交；另一标签页不能重复或修改。');await rate('game-answer:'+user.id,30,3600000);const g=combineGuards(roundGuard(),activeParticipant,sourceGuard,{sql:'NOT EXISTS(SELECT 1 FROM event_game_answers WHERE game_id=? AND ordinal=? AND user_id=?)',args:[game.id,current.ordinal,user.id]});return{body:{actorId:user.id,submitted:true},guard:g,statements:[stmt('INSERT INTO event_game_answers(game_id,ordinal,user_id,author_name,payload_json,created_at) VALUES(?,?,?,?,?,?)',game.id,current.ordinal,user.id,user.name,JSON.stringify(payload),now()),...(game.type==='relay'?[stmt("UPDATE event_game_rounds SET status='revealed',revision=revision+1 WHERE game_id=? AND ordinal=?",game.id,current.ordinal),...(current.ordinal>=game.round_limit?[stmt("UPDATE event_games SET phase='completed',finish_reason='round-limit',revision=revision+1,updated_at=? WHERE id=?",now(),game.id)]:[])]:[])]};});
 }
 if(!host)fail(403,'GAME_HOST_REQUIRED','只有发起者或本聊天室主办方可以推进轮次。');
 if(action==='reveal'){
  keys(d,['revision','revealConsent']);if(game.type!=='preference'||d.revealConsent!==true)fail(400,'INVALID_REVEAL','请明确结束选择并揭晓合计，不展示个人评分。');return mutate(d,async()=>{revision(current,d.revision);if(current.status!=='open')fail(409,'ROUND_REVEALED','本轮已揭晓。');const count=await get('SELECT COUNT(*) n FROM event_game_answers a JOIN event_game_players p ON p.game_id=a.game_id AND p.user_id=a.user_id WHERE a.game_id=? AND a.ordinal=? AND '+eligible.sql,game.id,current.ordinal,...eligible.args);if(count.n<2)fail(409,'TWO_ANSWERS_REQUIRED','至少两位仍在场的参与者作答后才能揭晓；无票不虚构结果。');return{body:{actorId:user.id,revealed:true},guard:combineGuards(roundGuard(),{sql:'(SELECT COUNT(*) FROM event_game_answers a JOIN event_game_players p ON p.game_id=a.game_id AND p.user_id=a.user_id WHERE a.game_id=? AND a.ordinal=? AND '+eligible.sql+')>=2',args:[game.id,current.ordinal,...eligible.args]}),statements:[stmt('DELETE FROM event_game_answers WHERE game_id=? AND ordinal=? AND user_id NOT IN(SELECT p.user_id FROM event_game_players p WHERE p.game_id=? AND '+eligible.sql+')',game.id,current.ordinal,game.id,...eligible.args),stmt("UPDATE event_game_rounds SET status='revealed',revision=revision+1,reason='host-reveal' WHERE game_id=? AND ordinal=?",game.id,current.ordinal),...(current.ordinal>=game.round_limit?[stmt("UPDATE event_games SET phase='completed',finish_reason='round-limit',revision=revision+1,updated_at=? WHERE id=?",now(),game.id)]:[])]};});
 }
 if(action==='skip'){
  keys(d,['revision','reason','skipConsent']);if(game.type!=='relay'||d.skipConsent!==true)fail(400,'INVALID_SKIP','请明确跳过本轮，并留下管理原因；不会代答。');const reason=musicText(fail,d.reason,100,true);return mutate(d,async()=>{revision(current,d.revision);if(current.status!=='open')fail(409,'ROUND_ENDED','本轮已经结束。');return{body:{actorId:user.id,skipped:true},guard:roundGuard(),statements:[stmt("UPDATE event_game_rounds SET status='skipped',reason=?,revision=revision+1 WHERE game_id=? AND ordinal=?",reason,game.id,current.ordinal),...(current.ordinal>=game.round_limit?[stmt("UPDATE event_games SET phase='cancelled',finish_reason='last-turn-skipped',revision=revision+1,updated_at=? WHERE id=?",now(),game.id)]:[])]};});
 }
 if(action==='next'){
  keys(d,['revision','nextConsent']);if(d.nextConsent!==true)fail(400,'NEXT_CONSENT_REQUIRED','请明确开始下一轮。');return mutate(d,async()=>{revision(current,d.revision);if(current.status==='open'||current.ordinal>=game.round_limit)fail(409,'ROUND_NOT_READY','本轮尚未结束或已达到本局上限。');const roster=await players();if(roster.length<2)fail(409,'TWO_PLAYERS_REQUIRED','不足两位参与者，请结束本局。');const next=game.type==='relay'?roster[(Math.max(0,roster.findIndex(p=>p.user_id===current.turn_user_id))+1)%roster.length].user_id:null;return{body:{actorId:user.id,next:true},guard:combineGuards(roundGuard(),{sql:'(SELECT COUNT(*) FROM event_game_players p WHERE game_id=? AND '+eligible.sql+')>=2',args:[game.id,...eligible.args]}),statements:[stmt('INSERT INTO event_game_rounds(game_id,ordinal,turn_user_id) VALUES(?,?,?)',game.id,current.ordinal+1,next),stmt('UPDATE event_games SET revision=revision+1,updated_at=? WHERE id=?',now(),game.id)]};});
 }
 return null;
}
