import {escape as esc} from '../avatar/model.js';
import {renderAvatarSvg} from '../illustrated-avatar/index.js';
import {createChatController} from '../event-client/chat-controller.js';
export function pendingSavedMessageNotice(state){
 const result=state.lastResult,current=state.current;
 return result?.type==='send'&&result.saved===true&&current?.peerId===result.peerId&&!current.messages.some(m=>m.id===result.messageId)
  ?'服务已收到上一条，无需重发。'
  :null;
}
/** A quiet textual conversation. No presence claims, implicit receipts or media grants. */
export function createChatPanel({container,onUnread=()=>{},onClose=()=>{},onPeople=()=>{},onRecap=()=>{}}){
 const client=createChatController();let state=client.getState(),opened=false,mode='list',lastFocus,messageSignature='',listSignature='',observer,ackTimer,pollTimer,pollBusy=false,disposed=false,ackPending=new Set(),lastPeer,expandedList=false;
 const root=document.createElement('section');root.className='private-chat';root.hidden=true;root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-label','私聊');container.append(root);
 root.innerHTML='<header><button class="chat-back" aria-label="返回对话列表">←</button><div><small>ONE TO ONE</small><h2>我们的对话</h2></div><button class="chat-close" aria-label="关闭私聊">×</button></header><div class="chat-notice"></div><div class="chat-conversations"></div><div class="chat-thread" hidden><button class="chat-older">更早的消息</button><div class="chat-messages" aria-label="消息记录"></div></div><div class="chat-problem" role="status"></div><div class="chat-pending"></div><form class="chat-composer"><label for="chat-text">留一句话</label><textarea id="chat-text" placeholder="比如，刚刚哪首歌最喜欢？" maxlength="1000" rows="2"></textarea><div><small>互相接受后就能私聊</small><button type="submit">发送 ↗</button></div></form><footer><button class="chat-more" data-chat-recap>回看这一晚</button></footer>';
 const q=s=>root.querySelector(s), thread=q('.chat-thread'),messages=q('.chat-messages'),composer=q('textarea');
 // Where the thread last came to rest (placed by a message render, or scrolled) and whether that was at the bottom. The rows below it
 // (.chat-problem, .chat-pending) shrink it without moving scrollTop, so while scrollTop is unchanged that verdict stands.
 // stickPeer: this panel has just sent that peer a message; the render that first shows it scrolls to the bottom.
 let restTop=0,restAtBottom=false,lastShown=null,stickPeer=null;const rest=()=>{restTop=thread.scrollTop;restAtBottom=thread.scrollHeight-restTop-thread.clientHeight<70;};
 const displayError=e=>{const saved=pendingSavedMessageNotice(state),transient=!e||['NETWORK','TIMEOUT','ABORTED'].includes(e.code)||e.status>=500;q('.chat-problem').textContent=saved&&transient?saved:e?.message||'';};
 const time=value=>new Date(value).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});
 function stop(){clearTimeout(pollTimer);clearTimeout(ackTimer);observer?.disconnect();ackPending.clear();}
 function visibleIncoming(){if(disposed||!opened||mode!=='thread'||document.hidden||!state.current)return [];const rect=thread.getBoundingClientRect(),height=window.innerHeight,width=window.innerWidth;return [...messages.querySelectorAll('[data-incoming]')].filter(node=>{const box=node.getBoundingClientRect();if(box.height<=0||box.top<Math.max(0,rect.top)||box.bottom>Math.min(height,rect.bottom)||box.left<0||box.right>width)return false;const hit=document.elementFromPoint((box.left+box.right)/2,(box.top+box.bottom)/2);return !!hit&&node.contains(hit);}).map(node=>node.dataset.message);}
 function visibleAck(){for(const id of visibleIncoming())ackPending.add(id);clearTimeout(ackTimer);if(ackPending.size)ackTimer=setTimeout(async()=>{const visible=new Set(visibleIncoming()),ids=[...ackPending].filter(id=>visible.has(id)).slice(0,50);ackPending.clear();if(!ids.length)return;try{await client.acknowledge(ids);}catch(e){displayError(e);}},350);}
 function schedule(){clearTimeout(pollTimer);if(!opened||document.hidden||disposed)return;pollTimer=setTimeout(refresh,4000);}
 async function refresh(){if(pollBusy||!opened||document.hidden||disposed||(mode==='thread'&&state.loading.includes('messages')))return;pollBusy=true;try{if(mode==='thread')await client.refresh();else if(!expandedList)await client.list();visibleAck();}catch(e){displayError(e);}finally{pollBusy=false;schedule();}}
 function render(next){if(next.actorId!==state.actorId||next.identityStatus!=='ready'){stop();messageSignature='';listSignature='';lastPeer=null;lastShown=null;stickPeer=null;messages.textContent='';composer.value='';q('.chat-conversations').innerHTML='';q('.chat-pending').innerHTML='';}state=next;const unread=state.list.totalUnreadCount??state.list.items.reduce((n,c)=>n+c.unreadCount,0);onUnread(unread);if(!opened)return;const c=state.current,show=mode==='thread'&&!!c;let placed=false;
 q('.chat-back').hidden=mode!=='thread';q('.chat-conversations').hidden=mode==='thread';thread.hidden=!show;q('.chat-composer').hidden=!show;q('header h2').textContent=show?c.chat?.peer?.name||'正在打开对话':'我们的对话';q('.chat-notice').textContent=show?(!c.loaded||!c.chat?'正在打开…':c.chat.canSend?'你们已经是朋友了。':'你们已经不是朋友了，只能看以前的消息。'):'从朋友的小人旁开始，接着聊刚才的那首歌。';
 const activePeer=document.activeElement?.dataset?.chatPeer,hadListFocus=q('.chat-conversations').contains(document.activeElement);const ls=JSON.stringify(state.list);if(ls!==listSignature){listSignature=ls;q('.chat-conversations').innerHTML=state.list.items.map(chat=>`<button data-chat-peer="${chat.userId}" class="chat-conversation"><span class="chat-avatar">${renderAvatarSvg(chat.peer.avatar,{view:'quarter',width:56,height:110})}</span><span><b>${esc(chat.peer.name)}</b><p>${esc(chat.lastMessage?.text||'还没有消息')}</p><small>${chat.canSend?'朋友':'以前的对话'}</small></span>${chat.unreadCount?`<i>${chat.unreadCount>99?'99+':chat.unreadCount}</i>`:''}</button>`).join('')||(state.list.loaded?'<div class="chat-empty"><span>↗</span><h3>还有话想和 TA 说。</h3><p>先去同场的人里打个招呼。</p><button class="chat-more" data-chat-people>看看同场的人</button></div>':'<p class="chat-empty">正在读取对话…</p>');if(state.list.nextCursor)q('.chat-conversations').innerHTML+='<button data-chat-more class="chat-more">查看更多对话</button>';if(expandedList)q('.chat-conversations').innerHTML+='<p class="chat-first">已暂停自动刷新。</p><button data-chat-refresh class="chat-more">刷新对话列表</button>';if(hadListFocus){const target=[...q('.chat-conversations').querySelectorAll('[data-chat-peer]')].find(n=>n.dataset.chatPeer===activePeer);(target||q('.chat-close')).focus();}}
 if(show){const changedPeer=lastPeer!==c.peerId,bottom=thread.scrollHeight-thread.scrollTop-thread.clientHeight<70||(restAtBottom&&Math.abs(thread.scrollTop-restTop)<1),oldHeight=thread.scrollHeight,oldTop=thread.scrollTop,viewportTop=thread.getBoundingClientRect().top,anchor=[...messages.querySelectorAll('[data-message]')].find(n=>n.getBoundingClientRect().bottom>viewportTop),anchorId=anchor?.dataset.message,anchorTop=anchor?.getBoundingClientRect().top;lastPeer=c.peerId;const signature=JSON.stringify([c.peerId,c.messages,c.chat?.receiptsAvailable]);if(signature!==messageSignature){messageSignature=signature;const sent=stickPeer===c.peerId&&c.messages.slice(c.messages.findIndex(m=>m.id===lastShown)+1).some(m=>m.senderId===state.actorId);lastShown=c.messages.at(-1)?.id??null;if(sent)stickPeer=null;messages.innerHTML=c.messages.map(m=>{const mine=m.senderId===state.actorId;return `<article class="chat-message ${mine?'mine':'theirs'}" data-message="${m.id}" ${!mine&&!m.readAt?'data-incoming="true"':''}><p>${esc(m.text)}</p>${!mine&&!m.readAt&&(m.text.length>250||m.text.split('\n').length>7)?`<button type="button" data-chat-read="${m.id}">这条长消息，我读完了</button>`:''}<small>${esc(time(m.createdAt))}${mine?` · ${c.chat?.receiptsAvailable&&m.readAt?'已读':'已发送'}`:''}</small></article>`;}).join('')||'<p class="chat-first">散场以后，也可以从这一句开始。</p>';if(changedPeer||bottom||sent)thread.scrollTop=thread.scrollHeight;else{const retained=[...messages.querySelectorAll('[data-message]')].find(n=>n.dataset.message===anchorId);thread.scrollTop=retained?oldTop+retained.getBoundingClientRect().top-anchorTop:oldTop;}placed=true;}
  q('.chat-older').hidden=!c.olderCursor;const editable=!!c.chat?.canSend&&!state.outbox.some(p=>p.peerId===c.peerId&&p.type==='send');composer.disabled=!c.chat?.canSend;if(composer.value!==state.draft&&document.activeElement!==composer)composer.value=state.draft||'';q('.chat-composer button').disabled=!editable||!composer.value.trim();q('.chat-composer small').textContent=c.chat?.canSend?'':'已不能发消息';q('.chat-pending').innerHTML=state.outbox.filter(p=>p.peerId===c.peerId).map(p=>`<div><span>${p.status==='running'?'正在发送…':esc(p.error?.message||'发送未确认，可以重试')}</span>${p.status!=='running'?`<button data-chat-retry="${p.id}">重试</button>${p.status==='failed'&&!p.error?.uncertain?`<button data-chat-discard="${p.id}">移除</button>`:''}`:''}</div>`).join('');visibleAck();}
 displayError(state.error||(!state.storage.ok?{message:state.storage.message}:null));if(placed)rest();schedule();
 }
 client.subscribe(render);
 async function open(peer){stop();lastFocus=document.activeElement;opened=true;root.hidden=false;messageSignature='';listSignature='';expandedList=false;mode=peer?'thread':'list';render(state);q('.chat-close').focus();try{client.syncIdentity();await(peer?client.open(peer):client.list());}catch(e){displayError(e);}schedule();}
 function close({restore=true}={}){if(!opened)return;opened=false;root.hidden=true;stop();client.close();mode='list';lastPeer=null;stickPeer=null;onClose();if(restore&&lastFocus?.isConnected)lastFocus.focus();}
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.hasAttribute('data-chat-people')){close();onPeople();}if(b?.hasAttribute('data-chat-recap')){const peer=state.current?.peerId;close();onRecap(peer);}});
 q('.chat-close').onclick=close;q('.chat-back').onclick=async()=>{stop();mode='list';client.close();render(client.getState());try{await client.list();}catch(e){displayError(e);}};
 q('.chat-older').onclick=()=>client.older().catch(displayError);
 q('.chat-conversations').addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.chatPeer)void open(b.dataset.chatPeer);if(b?.hasAttribute('data-chat-more')){expandedList=true;void client.list({cursor:state.list.nextCursor}).catch(displayError);}if(b?.hasAttribute('data-chat-refresh')){expandedList=false;void client.list().catch(displayError);}});
 q('.chat-pending').addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.chatRetry){if(state.outbox.some(p=>p.id===b.dataset.chatRetry&&p.type==='send'))stickPeer=state.current?.peerId;void client.retry(b.dataset.chatRetry).catch(error=>{stickPeer=null;displayError(error);});}if(b?.dataset.chatDiscard)try{client.discard(b.dataset.chatDiscard);}catch(error){displayError(error);}});
 composer.addEventListener('input',()=>{try{client.setDraft(composer.value);}catch(error){displayError(error);return;}q('.chat-composer button').disabled=!composer.value.trim()||!state.current?.chat?.canSend||state.outbox.some(p=>p.peerId===state.current?.peerId&&p.type==='send');});
 q('form').addEventListener('submit',async e=>{e.preventDefault();if(!composer.value.trim())return;stickPeer=state.current?.peerId;try{client.setDraft(composer.value);await client.send();composer.value=client.getState().draft||'';}catch(error){stickPeer=null;displayError(error);}});
 thread.addEventListener('scroll',visibleAck,{passive:true});thread.addEventListener('scroll',rest,{passive:true});
 messages.addEventListener('click',e=>{const button=e.target.closest('[data-chat-read]');if(button&&!document.hidden)void client.acknowledge([button.dataset.chatRead]).catch(displayError);});
 root.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();close();}if(e.key==='Tab'){const nodes=[...root.querySelectorAll('button:not([disabled]),textarea:not([disabled])')].filter(n=>n.getClientRects().length);if(!nodes.length)return;if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0].focus();}}});
 const visibility=()=>{if(document.hidden)stop();else if(opened)void refresh();};document.addEventListener('visibilitychange',visibility);
 return {open,close,syncIdentity(session){if(arguments.length)client.syncIdentity(session);else client.syncIdentity();},refresh:()=>opened&&expandedList?Promise.resolve():client.list().catch(()=>{}),getState:()=>client.getState(),dispose(){disposed=true;stop();document.removeEventListener('visibilitychange',visibility);client.dispose();root.remove();}};
}
