import './moderation-panel.css';
import {escape as esc} from '../avatar/model.js';
import {createModerationController} from '../event-client/moderation-controller.js';

const categories={'harassment':'骚扰或不友善行为','unwanted-content':'不合适的现场内容',privacy:'涉及隐私',spam:'重复或广告信息',other:'其他现场情况'};
const statusLabel={open:'等待房主查看',withdrawn:'我已撤回',resolved:'房主已移出 TA',dismissed:'房主已查看'};
const removalScope='只移出这一场，TA 在照片墙上的分享会撤下。';
export function createModerationPanel({container,getContext,onChanged=()=>{},onViewPhoto=()=>{}}){
 const client=createModerationController(),root=document.createElement('section');root.className='room-moderation';root.hidden=true;root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-label','本场反馈与管理');container.append(root);
 root.innerHTML='<header><div><small>这一场 / 彼此尊重</small><h2>本场反馈</h2></div><button data-mod-close aria-label="关闭反馈与管理">×</button></header><div class="moderation-body"></div><div class="moderation-problem" role="status"></div>';
 const q=s=>root.querySelector(s),body=q('.moderation-body');let state=client.getState(),opened=false,mode='reports',tab='reports',draft=null,confirmation=null,lastFocus,lastMarkup='',busy=false,refreshing=false,localError=null,pages={reports:[null],exclusions:[null],mine:[null]};
 const admissionPending=row=>state.pending.find(op=>['exclude','restore'].includes(op.type)&&op.roomId===row.roomId&&op.entityId===row.userId);
 const admissionWait='还有一步没完成，请先处理下方的记录。';
 function problem(error){localError=error?.message||null;q('.moderation-problem').textContent=localError||state.error?.message||(!state.storage.ok?state.storage.message:'');}
 const reportRow=(row,host)=>`<article class="moderation-record"><small>${esc(statusLabel[row.status])}</small><h3>${esc(row.targetName)}</h3><b>${esc(categories[row.category]||'现场反馈')}</b><p class="moderation-quote">${esc(row.details)}</p>${row.photoId?`<p class="moderation-fine">关于一张照片${getContext().room?.id===row.roomId&&getContext().photos.some(p=>p.id===row.photoId)?` <button data-mod-view-photo="${row.photoId}">查看照片</button>`:' · 这张照片看不到了。'}</p>`:''}${row.status==='open'?`<div class="moderation-actions">${host?`<button data-mod-report-remove="${row.id}">移出本场</button><button data-mod-dismiss="${row.id}">已查看，不移出</button>`:`<button data-mod-withdraw="${row.id}">撤回这项反馈</button>`}</div>`:''}</article>`;
 function pager(kind,value){return `<div class="moderation-pagination"><button data-mod-page="${kind}" data-dir="previous" ${pages[kind].length<=1?'disabled':''}>上一页</button><span>第 ${pages[kind].length} 页</span><button data-mod-page="${kind}" data-dir="next" ${!value.nextCursor?'disabled':''}>下一页</button></div>`;}
 function markup(){
  if(state.identityStatus!=='ready')return '<p>请先确认你的小人身份。</p>';
  if(mode==='feedback'){
   if(!draft)return '<p>请从同场的人或照片发起反馈。</p>';
   return `<p class="moderation-intro">关于 <b>${esc(draft.targetName)}</b>${draft.photoId?' 的这张现场照片':''}</p><p class="moderation-room">${esc(draft.roomTitle)}</p><p>只有本场房主会看到。</p><form><label>是什么情况？<select name="category">${Object.entries(categories).map(([value,label])=>`<option value="${value}" ${value===draft.category?'selected':''}>${label}</option>`).join('')}</select></label><label>告诉房主具体发生了什么<textarea name="details" maxlength="280" rows="5" placeholder="说说现场发生了什么">${esc(draft.details)}</textarea></label><small data-mod-count>${[...draft.details].length} / 280</small><label class="moderation-consent"><input type="checkbox" name="consent" ${draft.consent?'checked':''}><span>把这段说明交给本场房主</span></label><button class="moderation-primary" type="submit" ${!draft.consent||!draft.details.trim()||busy?'disabled':''}>提交给本场房主</button></form>`;
  }
  if(mode==='reports')return `<p>只有对应场次的房主能看到。</p>${state.reports.items.map(row=>reportRow(row,false)).join('')||(state.reports.loaded?'<p class="moderation-empty">你还没有提交过现场反馈。</p>':'<p>正在读取…</p>')}${pager('mine',state.reports)}<button data-mod-refresh>刷新这一页</button>`;
  const management=state.management;if(!management?.loaded)return '<p>正在读取…</p><button data-mod-refresh>重新读取</button>';
  const ctx=getContext(),members=ctx.room?.id===management.room.id&&ctx.room.joined?ctx.members.filter(m=>m.id!==state.actorId):[];
  let html=`<p class="moderation-room">${esc(management.room.title)}</p><nav aria-label="本场管理分类">${[['reports','现场反馈'],['members','同场成员'],['exclusions','移出记录']].map(([id,label])=>`<button data-mod-tab="${id}" aria-pressed="${tab===id}">${label}</button>`).join('')}</nav>`;
  if(tab==='reports')html+=`${management.reports.items.map(row=>reportRow(row,true)).join('')||'<p class="moderation-empty">目前没有现场反馈。</p>'}${pager('reports',management.reports)}`;
  if(tab==='members')html+=`${members.length?`<div class="moderation-members">${members.map(m=>`<div><b>${esc(m.name)}</b><button data-mod-remove="${m.id}">移出本场</button></div>`).join('')}</div>`:'<p>暂时没有可移出的成员。</p>'}<p class="moderation-fine">${removalScope}</p>`;
  if(tab==='exclusions')html+=`${management.exclusions.items.map(row=>`<article class="moderation-record"><h3>${esc(row.targetName)}</h3><p>${row.active?'已移出，不能再加入':'可以重新加入'}</p>${row.active?`<button data-mod-restore="${row.userId}" ${admissionPending(row)?'disabled':''}>允许重新加入</button>${admissionPending(row)?`<p class="moderation-fine" role="status">${admissionWait}</p>`:''}`:''}</article>`).join('')||'<p class="moderation-empty">本场没有移出记录。</p>'}${pager('exclusions',management.exclusions)}`;
  return html+'<button data-mod-refresh>刷新</button>';
 }
 function confirmationMarkup(){if(!confirmation)return '';const c=confirmation,text=c.type==='exclude'?removalScope:c.type==='restore'?'TA 可以重新加入这一场。':c.type==='withdraw'?'撤回后，房主会看到它已撤回。':'不移出，结束这项反馈。';return `<aside class="moderation-confirm"><h3>${esc(c.title)}</h3><p>${text}</p>${c.type==='restore'&&admissionPending(c.exclusion)?`<p role="status">${admissionWait}</p>`:''}<button class="moderation-primary" data-mod-confirm ${busy||c.type==='restore'&&admissionPending(c.exclusion)?'disabled':''}>${esc(c.button)}</button><button data-mod-cancel>再想想</button></aside>`;}
 function pendingMarkup(){return state.pending.map(op=>`<div class="moderation-pending"><b>${esc(op.label)}</b><p>${op.status==='running'?'正在确认…':esc(op.error?.message||'结果未确认，可以重试')}</p>${op.status!=='running'?`<button data-mod-retry="${op.id}">重试</button>${op.status==='failed'&&!op.error?.uncertain?`<button data-mod-discard="${op.id}">移除</button>`:''}`:''}</div>`).join('');}
 function render(){if(!opened)return;q('header h2').textContent=mode==='feedback'?'向本场房主反馈':mode==='manage'?'管理这一场':'我提交的反馈';const active=document.activeElement,key=active?.dataset?JSON.stringify([active.name||'',active.dataset]):null,had=body.contains(active),start=active?.selectionStart,end=active?.selectionEnd,scroll=body.scrollTop,html=markup()+confirmationMarkup()+pendingMarkup();if(html!==lastMarkup){body.innerHTML=html;lastMarkup=html;body.scrollTop=scroll;if(had){const next=[...body.querySelectorAll('button,textarea,select,input')].find(n=>JSON.stringify([n.name||'',n.dataset])===key);(next||q('[data-mod-close]')).focus();if(next?.setSelectionRange&&typeof start==='number')try{next.setSelectionRange(start,end);}catch{}}}problem(localError?{message:localError}:null);}
 client.subscribe(next=>{if(next.actorId!==state.actorId||next.identityStatus!=='ready'){draft=null;confirmation=null;lastMarkup='';}state=next;render();});
 function begin(nextMode){lastFocus=document.activeElement;opened=true;mode=nextMode;root.hidden=false;localError=null;lastMarkup='';confirmation=null;client.syncIdentity();q('[data-mod-close]').focus();}
 async function openReports(){client.close();draft=null;pages.mine=[null];begin('reports');render();try{await client.reports();}catch(error){problem(error);}}
 async function openManagement(roomId){client.close();draft=null;tab='reports';pages.reports=[null];pages.exclusions=[null];begin('manage');render();try{await client.management(roomId);}catch(error){problem(error);}}
 function openFeedback(target,{photoId=null}={}){const ctx=getContext();if(!ctx.room?.joined||!ctx.members.some(m=>m.id===target?.id)||target.id===ctx.actorId)throw Error('请从当前现场选择另一位成员。');if(ctx.room.hostId===target.id)throw Error('这是本场房主，你可以屏蔽 TA 或离场。');if(photoId&&!ctx.photos.some(p=>p.id===photoId&&p.ownerId===target.id&&p.visibility==='members'))throw Error('这张照片看不到了。');client.close();begin('feedback');draft={roomId:ctx.room.id,roomTitle:ctx.room.title,targetId:target.id,targetName:target.name,photoId,category:'other',details:'',consent:false};render();}
 function close({restore=true}={}){if(!opened)return;opened=false;root.hidden=true;client.close();draft=null;confirmation=null;body.innerHTML='';lastMarkup='';if(restore&&lastFocus?.isConnected)lastFocus.focus();}
 async function refresh(){if(!opened||document.hidden||busy||refreshing||mode==='feedback'||confirmation)return;refreshing=true;try{if(mode==='manage'&&!state.management?.loaded)await client.management(state.management?.room.id);else await client.refresh();}catch(error){problem(error);}finally{refreshing=false;}}
 async function mutate(fn,{reportSubmitted=false}={}){if(busy)return;busy=true;localError=null;render();let receipt=null;try{const result=await fn();receipt=result;if(!opened||result?.applied===false)return;confirmation=null;await onChanged(result);if(reportSubmitted){draft=null;mode='reports';pages.mine=[null];client.close();await client.reports();}else if(mode==='manage')await client.refresh();else await client.reports({cursor:pages.mine.at(-1)});if(result.committed&&!result.currentConfirmed)problem({message:'服务已收到，无需重复提交。'});}catch(error){problem(receipt?.committed?{message:'服务已收到，列表稍后更新。'}:error);}finally{busy=false;render();}}
 root.addEventListener('input',e=>{if(mode!=='feedback'||!draft)return;if(e.target.name==='details'){draft.details=e.target.value;q('[data-mod-count]').textContent=[...draft.details].length+' / 280';}if(e.target.name==='category')draft.category=e.target.value;if(e.target.name==='consent')draft.consent=e.target.checked;const button=q('button[type=submit]');if(button)button.disabled=!draft.consent||!draft.details.trim()||busy;});
 root.addEventListener('submit',e=>{e.preventDefault();if(mode!=='feedback'||!draft||!draft.consent||!draft.details.trim())return;const ctx=getContext();if(ctx.actorId!==state.actorId||ctx.room?.id!==draft.roomId||!ctx.room.joined){problem({message:'有变化，请重新打开。'});return;}const value={...draft};void mutate(()=>client.submitReport(value.roomId,{targetId:value.targetId,photoId:value.photoId,category:value.category,details:value.details,reportConsent:true},`向房主反馈 ${value.targetName}`),{reportSubmitted:true});});
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
  if(b.hasAttribute('data-mod-close'))close();if(b.dataset.modTab){confirmation=null;tab=b.dataset.modTab;render();}
  if(b.hasAttribute('data-mod-refresh'))void refresh();
  if(b.dataset.modPage){const kind=b.dataset.modPage,value=kind==='mine'?state.reports:state.management?.[kind];if(!value)return;if(b.dataset.dir==='next'&&value.nextCursor)pages[kind].push(value.nextCursor);else if(b.dataset.dir==='previous'&&pages[kind].length>1)pages[kind].pop();void(kind==='mine'?client.reports({cursor:pages.mine.at(-1)}):client.managementPage(kind,pages[kind].at(-1))).catch(problem);}
  if(b.dataset.modRemove){const target=getContext().members.find(m=>m.id===b.dataset.modRemove);if(target){confirmation={type:'exclude',roomId:state.management.room.id,target:{...target},title:`将 ${target.name} 移出这一场？`,button:'确认移出本场'};render();}}
  for(const [attribute,type]of[['modReportRemove','exclude'],['modDismiss','dismiss'],['modWithdraw','withdraw']])if(b.dataset[attribute]){const report=(mode==='manage'?state.management.reports.items:state.reports.items).find(row=>row.id===b.dataset[attribute]);if(report){confirmation={type,roomId:report.roomId,report:{...report},target:{id:report.targetId,name:report.targetName},title:type==='exclude'?`将 ${report.targetName} 移出这一场？`:type==='dismiss'?'结束这项反馈？':'撤回这项反馈？',button:type==='exclude'?'确认移出':type==='dismiss'?'确认，不移出':'确认撤回'};render();}}
  if(b.dataset.modRestore){const row=state.management?.exclusions.items.find(x=>x.userId===b.dataset.modRestore);if(row&&admissionPending(row)){problem({message:admissionWait});render();return;}if(row){confirmation={type:'restore',exclusion:{...row},title:`允许 ${row.targetName} 重新加入？`,button:'允许重新加入'};render();}}
  if(b.hasAttribute('data-mod-cancel')){confirmation=null;render();}
  if(b.hasAttribute('data-mod-confirm')&&confirmation){const value=confirmation;if(value.type==='restore'&&admissionPending(value.exclusion)){problem({message:admissionWait});render();return;}void mutate(()=>value.type==='exclude'?client.exclude(value.roomId,value.target,{report:value.report,removalConsent:true}):value.type==='restore'?client.restore(value.exclusion,{allowReentryConsent:true}):client.reportAction(value.type,value.report,value.target.name));}
  if(b.dataset.modViewPhoto){const id=b.dataset.modViewPhoto,ctx=getContext();if(ctx.photos.some(p=>p.id===id)){close({restore:false});onViewPhoto(id);}}
  if(b.dataset.modRetry)void mutate(()=>client.retry(b.dataset.modRetry));if(b.dataset.modDiscard)try{client.discard(b.dataset.modDiscard);}catch(error){problem(error);}
 });
 root.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();close();}if(e.key==='Tab'){const nodes=[...root.querySelectorAll('button:not([disabled]),textarea:not([disabled]),select:not([disabled]),input:not([disabled])')].filter(n=>n.getClientRects().length);if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus();}}});
 return{openReports,openManagement,openFeedback,close,refresh,syncIdentity(value){if(arguments.length)client.syncIdentity(value);else client.syncIdentity();},getState:()=>client.getState(),dispose(){opened=false;client.dispose();root.remove();}};
}
