import {escape as esc} from '../avatar/model.js';
/** Member text is clearly separate from the four source-backed relationship cards. */
export function createMusicTopics({container,controller,onError=()=>{},onDiscuss=()=>{}}){
 let root=null,archived=false,trackedRoom=false,scope=null,actor=null,epoch=0,privacy='',back=null,topics=[],selected=null,cursor=null,before=null,error='',notice='',busy=false,pending=null,timer,abort;
 let draft={title:'',artist:'',note:''};const base=()=>`/${scope.kind==='room'?'rooms':'communities'}/${scope.id}/topics`,prefix=()=>`music-space-topic-operation:v1:${actor}:${scope.kind}:${scope.id}:`,draftKey=()=>`music-space-topic-draft:v1:${actor}:${scope.kind}:${scope.id}`;
 function readPending(){for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith(prefix())){const p=JSON.parse(localStorage.getItem(k));if(p.actor===actor&&p.key)return {...p,storageKey:k};}}return null;}
 function render(){if(!root)return;const scroll=root.querySelector('.community-scroll')?.scrollTop||0,expanded=root.querySelector('details')?.open,active=document.activeElement?.name,start=document.activeElement?.selectionStart;const host=scope.hostId===actor||scope.kind==='room'&&controller.getState().room?.hostId===actor;
  root.innerHTML=`<header><span class="eyebrow">MUSIC / 从一首歌接着说</span><button data-topic="close" aria-label="回到聊天室">×</button></header><div class="community-scroll"><h2>音乐话题</h2>${error?`<p role="alert">${esc(error)}</p><button data-topic="refresh">重新读取</button>`:''}${notice?`<p role="status">${esc(notice)}</p>`:''}${pending?'<p role="status">上一步还没确认，可以重试。</p><button data-topic="retry">重试</button>':''}${archived?'<p role="status">社群已归档。</p>':''}${topics.map(t=>`<article class="music-reference"><small>成员自填</small><h3>${esc(t.title)}</h3><p>${esc(t.artist)}</p><p>${esc(t.note)}</p><small>${esc(t.authorName)} 留下的话题</small><button data-topic-discuss="${t.id}" ${busy||pending?'disabled':''}>带回聊天室聊</button>${t.authorId===actor||host?`<button data-topic-withdraw="${t.id}" ${busy||pending?'disabled':''}>撤回这个话题</button>`:''}</article>`).join('')||(!error?'<p>还没有话题。留一首让你想起今晚的歌吧。</p>':'')}${cursor?'<button data-topic="older">看更早的话题</button>':''}${before?'<button data-topic="newest">回到最新话题</button>':''}<details><summary>留下我的音乐话题</summary><form data-topic-create><label>音乐名称<input name="title" maxlength="80" required value="${esc(draft.title)}"></label><label>音乐人（可留空）<input name="artist" maxlength="80" value="${esc(draft.artist)}"></label><label>我想聊的一句话<input name="note" maxlength="300" required value="${esc(draft.note)}"></label><label><input name="consent" type="checkbox" required>发到聊天室</label><button ${busy||pending||error||archived?'disabled':''}>发布</button></form></details><button data-topic="refresh">刷新</button><button data-topic="close">回到聊天室</button></div>`;if(root.querySelector('details'))root.querySelector('details').open=expanded||false;root.querySelector('.community-scroll').scrollTop=scroll;if(active){const n=root.querySelector(`[name="${active}"]`);n?.focus();if(n?.type==='text'&&start!==null)n.setSelectionRange(start,start);}}
 async function refresh(){if(!root||busy)return;const gen=epoch;try{try{pending=pendingFromDisk();}catch{}const result=await controller.communityRequest(base()+(selected?'/'+selected:before?'?before='+before:''));if(gen!==epoch)return;archived=result.archived;topics=selected?[result.topic]:result.topics;cursor=result.nextCursor;error='';render();}catch(e){if(gen===epoch){topics=[];error=e.message;render();}}finally{clearTimeout(timer);if(root&&gen===epoch&&!document.hidden)timer=setTimeout(refresh,5000);}}
 function clear(p){try{localStorage.removeItem(p.storageKey);}catch{notice='服务器已确认。';}if(pending===p)pending=null;}
 async function write(path,payload,method='POST',retry=false){if(busy||pending&&!retry)return;const gen=epoch,captured=JSON.stringify(draft);busy=true;abort=new AbortController();let op;try{if(!retry){const key=crypto.randomUUID();op={actor,path,data:payload,method,key,storageKey:prefix()+key};localStorage.setItem(op.storageKey,JSON.stringify(op));pending=op;}op=pending;render();await controller.communityRequest(op.path,{method:op.method,data:op.data,key:op.key,signal:abort.signal});clear(op);if(gen!==epoch)return;if(op.method==='POST'&&captured===JSON.stringify(draft)&&JSON.stringify({title:op.data.title,artist:op.data.artist,note:op.data.note})===captured&&localStorage.getItem(draftKey())===captured){draft={title:'',artist:'',note:''};saveDraft();}if(op.method==='DELETE')selected=null;notice='服务器已确认。';pending=readPending();error='';}catch(e){if(op&&!e.uncertain&&!abort.signal.aborted)clear(op);if(gen===epoch){error=e.message;render();}onError(e);}finally{busy=false;if(gen===epoch){render();await refresh();}}}
 function saveDraft(){try{localStorage.setItem(draftKey(),JSON.stringify(draft));}catch{notice='草稿没存上，关闭前请先复制。';}}
 function close(){epoch++;clearTimeout(timer);abort?.abort();root?.remove();root=null;topics=[];const callback=back;back=null;callback?.();}
 async function open(next,returnTo,id=null){if(busy)return;close();scope=next;trackedRoom=scope.kind==='room'&&controller.getState().room?.id===scope.id;selected=id;before=null;actor=controller.getState().identity.user?.id;privacy=JSON.stringify(controller.getState().social?.blocks||[]);back=returnTo;error=notice='';draft={title:'',artist:'',note:''};try{const saved=JSON.parse(localStorage.getItem(draftKey())||'null');if(saved&&typeof saved.title==='string')draft=saved;pending=readPending();}catch{pending=null;notice='草稿没能读取。';}root=document.createElement('section');root.className='community-panel music-topics';root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-label','音乐话题');container.append(root);
  root.addEventListener('input',e=>{const f=e.target.form;if(!f?.hasAttribute('data-topic-create'))return;const d=new FormData(f);draft={title:d.get('title'),artist:d.get('artist'),note:d.get('note')};saveDraft();});root.addEventListener('submit',e=>{e.preventDefault();e.stopPropagation();const d=new FormData(e.target);if(d.get('consent')==='on')void write(base(),{title:d.get('title'),artist:d.get('artist'),note:d.get('note'),publishConsent:true});});
  root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;e.stopPropagation();const action=b.dataset.topic;if(action==='close')close();if(action==='refresh')void refresh();if(action==='retry'&&pending)void write(pending.path,pending.data,pending.method,true);if(action==='older'){before=cursor;selected=null;void refresh();}if(action==='newest'){before=null;selected=null;void refresh();}if(b.dataset.topicDiscuss){const t=topics.find(t=>t.id===b.dataset.topicDiscuss);close();onDiscuss(t);}if(b.dataset.topicWithdraw&&confirm('撤回这个话题？')){const t=topics.find(t=>t.id===b.dataset.topicWithdraw);void write(base()+'/'+t.id,{revision:t.revision},'DELETE');}});
  root.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();close();}if(e.key==='Tab'){const ns=[...root.querySelectorAll('button:not([disabled]),input,summary')].filter(n=>n.getClientRects().length);if(e.shiftKey&&document.activeElement===ns[0]){e.preventDefault();ns.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===ns.at(-1)){e.preventDefault();ns[0]?.focus();}}});render();root.querySelector('button')?.focus();await refresh();
 }
 const visible=()=>{clearTimeout(timer);if(root&&!document.hidden)void refresh();};document.addEventListener('visibilitychange',visible);
 return{open,close,syncIdentity(){const s=controller.getState();if(root&&(actor!==s.identity.user?.id||privacy!==JSON.stringify(s.social?.blocks||[])||trackedRoom&&(s.room?.id!==scope.id||!s.members.some(m=>m.id===actor)))){back=null;close();}},dispose(){back=null;close();document.removeEventListener('visibilitychange',visible);}};
}
