import {realArtists,realSongs,realEdges,REAL_CATALOGUE_VERSION} from '../../runtime-preview/src/map-catalogue.js';
import {networkLayout,shortestChain} from '../music-map/map-network.js';
import {escape as esc} from '../avatar/model.js';
const byId=Object.fromEntries(realArtists.map(a=>[a.id,a]));
/** Public, versioned metadata. No audio, private photos, external graph calls or Map storage. */
export function createMusicMap({container,controller,onShare=()=>{},onRelay=()=>{}}){
 const root=document.createElement('section');root.className='music-map';root.hidden=true;root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-label','Music Map 音乐关系探索');container.append(root);
 let opened=false,focus,actor,scope=null,back=null,selected='real-jay',songId=null,history=[],all=false,zoom=1,pan={x:0,y:0},gesture=null,dragged=false,target='';
 const positions=networkLayout('real');const mobile=()=>matchMedia('(max-width:700px)').matches;const center=()=>mobile()&&!all?[250,225]:[500,310];
 function nodes(){if(all)return positions.map(a=>({...a,px:500+a.x*260,py:310+a.z*230}));const related=realEdges.filter(e=>e.a===selected||e.b===selected),ids=[...new Set(related.map(e=>e.a===selected?e.b:e.a))];const [cx,cy]=center(),rx=mobile()?175:245,ry=mobile()?175:200;return [{...byId[selected],px:cx,py:cy},...ids.map((id,i)=>({...byId[id],px:cx+rx*Math.cos(2*Math.PI*i/ids.length-.7),py:cy+ry*Math.sin(2*Math.PI*i/ids.length-.7)}))];}
 function detail(){const a=byId[selected],relationships=realEdges.filter(e=>e.a===selected||e.b===selected),song=realSongs[songId];return `<div class="map-person"><span class="eyebrow">FOLLOW A VOICE / ${relationships.length} 条录音关系</span><h2>${esc(a.name)}</h2><p>${esc(a.bio)}</p></div>${song?`<article class="map-recording"><small>已留档的共同演唱 · ${song.checkedAt}</small><h3>《${esc(song.title)}》</h3><p>${song.artists.map(id=>esc(byId[id].name)).join(' / ')}</p><p class="recording-version">${esc(song.recordingLabel)}</p><p>${esc(song.evidence)}</p><details><summary>署名与资料出处</summary><p>${esc(song.creditSummary)}</p>${song.credits.map(c=>`<p>${esc(c.name)} · ${esc(c.role)}</p>`).join('')}${song.creditSources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label)} ↗ <small>${esc(s.checkedAt||song.checkedAt)}</small></a>`).join('')}</details><p class="fine">这里只展示历史核对的元数据，不含音频、歌词或真实封面；出处是否可访问取决于原站。</p>${scope?`<button data-map="share" class="map-primary">把这份发现带回聊天 ↗</button><button data-map="relay">用这首录音开始关系接龙 ↗</button><p class="fine">只准备草稿，分享与开局仍由你明确确认。</p>`:'<p class="fine">加入并打开一个聊天室后，可主动分享或接续关系接龙。</p>'}</article>`:'<p class="map-prompt">选一条连线或下面的一首歌，看看两种声音在哪里相遇。</p>'}<div class="map-links">${relationships.map(e=>{const other=e.a===selected?e.b:e.a;return `<article><button data-map-song="${e.song}" class="${songId===e.song?'selected':''}"><span>${esc(byId[other].name)}</span><b>《${esc(realSongs[e.song].title)}》</b><small>${esc(realSongs[e.song].recordingLabel)}</small></button><button data-map-node="${other}" aria-label="沿关系探索${esc(byId[other].name)}">↗</button></article>`;}).join('')}</div>`;}
 function render(){if(!opened)return;const scroll=root.querySelector('.map-detail')?.scrollTop||0,ns=nodes(),coords=Object.fromEntries(ns.map(n=>[n.id,n])),links=realEdges.filter(e=>coords[e.a]&&coords[e.b]);const chain=target?shortestChain(selected,target,'real'):null;
 root.innerHTML=`<header><div><span class="eyebrow">MUSIC MAP / 沿一首歌，遇见下一种声音</span><h1>音乐之间，有路可走。</h1></div><button data-map="close" aria-label="关闭音乐探索">×</button></header><div class="map-toolbar"><button data-map="back" ${history.length?'':'disabled'}>← 上一个发现</button><button data-map="overview">${all?'回到身边的关系':'看看完整关系图'}</button><label>找音乐人<select data-map-search>${realArtists.map(a=>`<option value="${a.id}" ${selected===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label><label>沿目录找路径<select data-map-target><option value="">选另一位音乐人</option>${realArtists.filter(a=>a.id!==selected).map(a=>`<option value="${a.id}" ${target===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label></div>${target?`<div class="map-chain">${chain?`这份目录内的最短路径：${chain.nodes.map(id=>`<button data-map-node="${id}">${esc(byId[id].name)}</button>`).join(' → ')} · ${chain.edges.length} 条共同演唱录音`:'当前目录没有连通路径；不代表现实中没有合作。'}</div>`:''}<div class="map-body"><div class="map-board"><div class="map-viewport" aria-label="可拖动的音乐关系图；也可用音乐人选择框和关系列表导航"><svg viewBox="${mobile()&&!all?'0 0 500 450':'0 0 1000 620'}" role="group" aria-label="${all?'29位音乐人的完整目录':'当前音乐人身边的共同演唱关系'}"><g class="map-transform" transform="translate(${pan.x} ${pan.y}) translate(${center()[0]} ${center()[1]}) scale(${zoom}) translate(${-center()[0]} ${-center()[1]})">${links.map(e=>`<g class="map-edge ${songId===e.song?'selected':''}" role="button" tabindex="0" data-map-song="${e.song}" aria-label="查看《${esc(realSongs[e.song].title)}》关系"><line x1="${coords[e.a].px}" y1="${coords[e.a].py}" x2="${coords[e.b].px}" y2="${coords[e.b].py}"/><line class="map-edge-hit" x1="${coords[e.a].px}" y1="${coords[e.a].py}" x2="${coords[e.b].px}" y2="${coords[e.b].py}"/></g>`).join('')}${ns.map(a=>`<g class="map-node ${a.id===selected?'selected':''}" role="button" tabindex="0" data-map-node="${a.id}" aria-label="探索${esc(a.name)}" transform="translate(${a.px} ${a.py})"><circle r="${a.id===selected?43:mobile()&&!all?36:29}"/><text y="5" text-anchor="middle">${esc(a.name)}</text><text class="map-degree" y="${a.id===selected?65:50}" text-anchor="middle">${a.songIds.length} 份录音</text></g>`).join('')}</g></svg></div><div class="map-controls"><button data-map="out" aria-label="缩小地图">−</button><button data-map="reset">复位</button><button data-map="in" aria-label="放大地图">＋</button><span>拖动关系图 · 用按钮缩放<br>页面滚动请在图外操作</span></div><p class="map-caption">29 位真实音乐人 / 37 条留档共同演唱关系<br><small>Music Map ${REAL_CATALOGUE_VERSION} · 不推测风格或现实合作全貌</small></p></div><aside class="map-detail">${detail()}</aside></div>`;
 root.querySelector('.map-detail').scrollTop=scroll;
 }
 function choose(id){if(!byId[id]||id===selected)return;history.push({selected,songId,all,zoom,pan:{...pan},target});selected=id;songId=null;target='';all=false;zoom=1;pan={x:0,y:0};render();root.querySelector('.map-detail').scrollTop=0;}
 function close(){opened=false;root.hidden=true;root.innerHTML='';container.classList.remove('map-open');const callback=back;back=null;scope=null;callback?.();focus?.focus();}
 function click(e){if(dragged){dragged=false;return;}const n=e.target.closest('[data-map-node],[data-map-song],[data-map]');if(!n)return;e.stopPropagation();if(n.dataset.mapNode)choose(n.dataset.mapNode);if(n.dataset.mapSong){songId=n.dataset.mapSong;render();root.querySelector('.map-detail').scrollTop=0;}const a=n.dataset.map;if(a==='close')close();if(a==='back'){const p=history.pop();if(p){({selected,songId,all,zoom,pan,target}=p);render();}}if(a==='overview'){all=!all;zoom=1;pan={x:0,y:0};render();}if(['in','out','reset'].includes(a)){zoom=a==='reset'?1:Math.min(2.4,Math.max(.65,zoom*(a==='in'?1.2:1/1.2)));if(a==='reset')pan={x:0,y:0};render();}if(a==='share'&&scope&&songId){const s={...scope},id=songId;close();onShare(s,id);}if(a==='relay'&&scope&&songId){const s={...scope},id=songId;close();onRelay(s,id);}}
 root.addEventListener('click',click);root.addEventListener('change',e=>{if(e.target.matches('[data-map-search]'))choose(e.target.value);if(e.target.matches('[data-map-target]')){target=e.target.value;render();}});
 root.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();close();}if((e.key==='Enter'||e.key===' ')&&e.target.matches('g[role=button]')){e.preventDefault();click(e);}if(e.key==='Tab'){const ns=[...root.querySelectorAll('button:not([disabled]),select,a,summary,g[tabindex]')].filter(n=>n.getClientRects().length);if(e.shiftKey&&document.activeElement===ns[0]){e.preventDefault();ns.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===ns.at(-1)){e.preventDefault();ns[0]?.focus();}}});
 root.addEventListener('pointerdown',e=>{const board=e.target.closest('.map-viewport');if(!board||e.button!==0)return;gesture={id:e.pointerId,x:e.clientX,y:e.clientY,pan:{...pan},board};dragged=false;});root.addEventListener('pointermove',e=>{if(!gesture||e.pointerId!==gesture.id)return;const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(Math.hypot(dx,dy)<6&&!dragged)return;if(!dragged)gesture.board.setPointerCapture(e.pointerId);dragged=true;const r=gesture.board.getBoundingClientRect(),scale=root.querySelector('svg').viewBox.baseVal.width/r.width;pan={x:Math.max(-650,Math.min(650,gesture.pan.x+dx*scale)),y:Math.max(-420,Math.min(420,gesture.pan.y+dy*scale))};root.querySelector('.map-transform')?.setAttribute('transform',`translate(${pan.x} ${pan.y}) translate(${center()[0]} ${center()[1]}) scale(${zoom}) translate(${-center()[0]} ${-center()[1]})`);});root.addEventListener('pointerup',()=>{gesture=null;});root.addEventListener('pointercancel',()=>{gesture=null;dragged=false;});
 return {open(next=null,returnBack=null,recordingId=null){focus=document.activeElement;scope=next;actor=controller.getState().identity.user?.id;back=returnBack;if(recordingId&&realSongs[recordingId]){songId=recordingId;selected=realSongs[recordingId].artists[0];}opened=true;root.hidden=false;container.classList.add('map-open');render();root.querySelector('[data-map=close]').focus();},close,syncIdentity(){if(opened&&actor!==controller.getState().identity.user?.id){back=null;close();}},dispose(){back=null;close();root.remove();}};
}
