import './style.css';
import {avatarSVG} from './avatar.js';
import {mountToonScene} from './three-scene.js';
import {KEY,SESSION_KEY,DEFAULT_AVATAR,TEMPLATES,COMPONENTS,GARMENT_COLORS,safeAvatar,withAvatarPart,applyLookPreset,SKINS,HAIRS,OUTFITS,POSES,SONGS,newDraft,readSaved,clone,escape as e,clamp} from './model.js';
import {request,photoBlob} from './api.js';
import {playMusic,stopMusic} from './audio.js';
import {exportImage} from './export.js';
// Asset imports are supplied by the scene-art task before final build.
const sceneAssets=import.meta.glob('./assets/*.webp',{eager:true,query:'?url',import:'default'});
const scenes=[{id:'rooftop-night',name:'晚风天台',hint:'城市很大，这里刚好容下两个人',tag:'BLUE HOUR',song:'late-train'}, {id:'sakura-night',name:'樱下放映',hint:'散场以后，副歌还在继续',tag:'AFTER THE SHOW',song:'sakura-echo'}, {id:'fan-stage',name:'想象音乐会',hint:'与原创虚构音乐人「月白」同台',tag:'FAN FICTION',song:'moon-window'}];
const $=s=>document.querySelector(s),app=$('#app'),modal=$('#modal');
const saved=readSaved();let profile=saved.profile||null,draft=saved.draft||newDraft(profile?.avatar),works=saved.works||[],session=saved.session||null;
let localDraft=clone(draft),pendingEdits=saved.pendingEdits||{},inviteLinks=saved.inviteLinks||{};
let toon=null,toonLayer=null,toonFailed=false,routeLoading=false,avatarEditing=false,avatarCategory='presets';const portraits=new Map();
let view='studio',tab='scene',connected=null,busy=false,playing=false,history=[],redo=[],remote=null,invite=null,inviteToken=null,inviteLink='',photoURL='',photoKey='',lastFocus=null,pollTimer=null,network=!navigator.onLine,storageFailed=false,routeGeneration=0;
const icons={plus:'M12 5v14M5 12h14',arrow:'M5 12h14m-6-6 6 6-6 6',back:'M19 12H5m6-6-6 6 6 6',close:'m6 6 12 12M18 6 6 18',check:'m5 12 4 4L19 6',photo:'M4 4h16v16H4zM4 16l5-5 4 4 3-3 4 4M8 8h.01',music:'M9 18V5l11-2v13M9 7l11-2M9 18c0 3-6 3-6 0s6-3 6 0M20 16c0 3-6 3-6 0s6-3 6 0',play:'m9 5 11 7-11 7z',pause:'M8 5v14M16 5v14',undo:'M8 5 3 10l5 5M3 10h10a7 7 0 0 1 7 7',redo:'m16 5 5 5-5 5M21 10H11a7 7 0 0 0-7 7',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',lock:'M6 10h12v11H6zM8 10V7a4 4 0 0 1 8 0v3',share:'M16 3h5v5M11 13 21 3M20 13v8H3V4h8',user:'M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8M4 21a8 8 0 0 1 16 0',star:'m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9z',grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',link:'M10 13a4 4 0 0 0 6 0l4-4a4 4 0 0 0-6-6l-2 2M14 11a4 4 0 0 0-6 0l-4 4a4 4 0 0 0 6 6l2-2',refresh:'M20 7v6h-6M4 17v-6h6M6 6a8 8 0 0 1 14 7M18 18a8 8 0 0 1-14-7',trash:'M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7'};
const ic=n=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round">${(icons[n]||icons.star).split('|').map(d=>`<path d="${d}"/>`).join('')}</svg>`;
const button=(name,text,cls='',attrs='')=>`<button data-action="${name}" class="${cls}" ${attrs}>${text}</button>`;
const song=()=>SONGS.find(s=>s.id===draft.songId)||SONGS[0];
const bgFor=scene=>scene?.kind==='photo'?(scene.dataUrl||(scene.photoUrl?photoURL:'')):sceneAssets[`./assets/${scene?.id==='fan-stage'?'sakura-night':scene?.id||'rooftop-night'}.webp`]||'';
function persist(){if(remote){if(isDirty())pendingEdits[remote.id]={avatar:clone(draft.avatar),transform:clone(draft.transform),response:draft.response||'',baseContentRevision:remote.contentRevision};else delete pendingEdits[remote.id];}try{localStorage.setItem(KEY,JSON.stringify({version:1,profile,draft:remote||invite?localDraft:draft,activeWork:remote?.id||null,pendingEdits,inviteLinks,works}));storageFailed=false;return true;}catch{storageFailed=true;toast('浏览器存储已满。当前画面还在，请先导出作品或释放空间。',true);return false;}}
function toast(text,error=false){const t=$('#toast');t.textContent=text;t.className=error?'visible error':'visible';clearTimeout(t.timer);t.timer=setTimeout(()=>t.className='',4500);}
function commit(change){history.push(clone(draft));if(history.length>40)history.shift();redo=[];change(draft);persist();render();}
function isDirty(){if(!remote)return false;const me=remote[remote.role];return JSON.stringify(safeAvatar(draft.avatar))!==JSON.stringify(safeAvatar(me.avatar))||JSON.stringify(draft.transform)!==JSON.stringify(me.transform)||(remote.role==='guest'&&(draft.response||'')!==(me.response||''));}
function requireClean(){if(!isDirty())return true;openModal(`<h2>先收好你的调整。</h2><p class="modal-intro">画面里还有未保存的改动。保存后，双方会确认这个新版本。</p><div class="modal-actions">${button('discard-shared','放弃这次调整','secondary')}${button('save-shared-modal','保存我的调整','primary')}</div>`);return false;}
function currentHost(){return invite?invite.host:remote?remote.host:{name:profile?.name||'你',avatar:draft.avatar,transform:draft.transform};}
function currentGuest(){if(invite)return {name:profile?.name||'我',avatar:draft.avatar,transform:draft.transform};if(remote?.guest)return remote.guest;if(draft.scene.id==='fan-stage')return {name:'月白 · 虚构音乐人',avatar:{skin:0,hair:3,hairColor:3,outfit:2,accessory:'none',pose:'sing'},transform:{x:68,y:80,scale:.92,rotation:3},fiction:true};return null;}
function isGuest(){return Boolean(invite||remote?.role==='guest');}
function myAvatar(){return draft.avatar;}
function statusLabel(){if(isDirty())return '有调整尚未保存';if(invite)return '入镜邀请';if(!remote)return '本机私密草稿';if(remote.exportEligible)return '已共同确认';if(remote.status==='pending')return isGuest()?'等待对方确认':'朋友已入镜';if(remote.status==='accepted')return '等待保存许可';if(remote.status==='rejected')return '可重新调整';return '等待朋友入镜';}
function render(){
 if(toonLayer?.parentNode)toonLayer.remove();
 const ss=draft.scene.kind==='photo'?{name:'我的现场',tag:'YOUR PHOTO'}:(scenes.find(s=>s.id===draft.scene.id)||scenes[0]);
 app.innerHTML=`<header class="topbar"><a class="brand" href="#" aria-label="Space 创作间"><span class="brand-mark"><i></i><i></i></span>space<span class="brand-sub">YOUR NEXT COVER</span></a><nav aria-label="主导航">${button('studio',`${ic('star')}创作间`,view==='studio'?'nav active':'nav')}${button('works',`${ic('grid')}我的作品 <span class="nav-count">${works.length}</span>`,view==='works'?'nav active':'nav')}</nav>${button('avatar',`<span class="profile-mini">${avatarSVG(profile?.avatar||DEFAULT_AVATAR)}</span><span>${e(profile?.name||'创建我的分身')}</span>`, 'profile-btn','aria-label="编辑我的分身"')}</header>
 ${routeLoading?`<div class="route-banner" role="status">正在读取这张共同作品… ${button('cancel-route','先回私密草稿','text-btn')}</div>`:''}${network?'<div class="network-banner" role="status">暂时离线 · 本机创作照常保存，邀请与共同作品将在联网后继续</div>':''}
 <main id="main" tabindex="-1" aria-busy="${routeLoading}" class="${routeLoading?'route-loading':''}">${view==='works'?worksPage():`<section class="studio-heading"><div><div class="eyebrow">SPACE / MUSIC × IDENTITY</div><h1>${invite?`${e(invite.host.name)} 给你留了个位置`:'今晚的封面，缺你。'}<span class="hand-star">✧</span></h1><p>${invite?'带上自己的分身，给这张作品一个你的回应。':'带着自己的样子，和朋友一起出演。'}</p></div><div class="connection"><i class="${connected?'online':''}"></i>${connected?'双人共创已连接':connected===null?'正在连接共创服务':'本机创作模式'}${button('about',ic('info'),'tiny','aria-label="了解保存与隐私"')}</div></section>
 <section class="workspace" aria-label="双人创作工作室"><aside class="identity-rail"><div class="rail-label">今晚的我 <span>01</span></div><button data-action="avatar" class="identity-card"><div class="avatar-pedestal">${avatarSVG(myAvatar())}<span class="spark s1">✧</span><span class="spark s2">+</span></div><strong>${e(profile?.name||'还没有名字的你')}</strong><span class="identity-edit">${profile?'换个造型':'创造你的分身'} ${ic('arrow')}</span></button><p class="rail-note">一个分身，<br>很多种登场方式。</p><div class="rail-divider"></div><div class="rail-label">你的出演方式</div><div class="pose-list">${POSES.map(([id,label])=>button('pose',`<span class="pose-dot">${{sway:'♫',wave:'✦',sing:'♪',listen:'☾'}[id]}</span>${label}`,draft.avatar.pose===id?'pose active':'pose',`data-value="${id}" aria-pressed="${draft.avatar.pose===id}"`)).join('')}</div><div class="rail-foot">${ic('lock')}默认私密 · 由你决定分享</div></aside>
 <div class="canvas-column"><div class="canvas-toolbar"><span class="canvas-tab">${ic('photo')} ${e(invite?.title||draft.title)}</span><div>${button('undo',ic('undo'),'icon-btn',`aria-label="撤销" ${history.length?'':'disabled'}`)}${button('redo',ic('redo'),'icon-btn',`aria-label="重做" ${redo.length?'':'disabled'}`)}${button('preview',ic('share'),'icon-btn','aria-label="放大预览"')}</div></div><div class="artboard-wrap"><div class="artboard ${playing?'music-playing':''}" style="--beat:${60/song().bpm}s" id="artboard" aria-label="作品画布"><div class="scene-bg" style="background-image:url('${e(bgFor(draft.scene))}')"></div><div class="scene-shade"></div><div class="scene-overline"><span>SPACE / ${e(ss.tag)}</span><span class="scene-number">NO. 001</span></div><div class="scene-caption"><span>${e(ss.name)}</span><strong>${e(invite?.caption||draft.caption)}</strong></div>${scenePeople()}<div class="scene-footer"><span>${draft.scene.kind==='photo'?'你的照片，新的故事':'原创虚构场景'}</span><span>STAY A LITTLE LONGER ↗</span></div></div></div><div class="canvas-hint">${ic('user')}拖动分身找个位置 <span>·</span> 方向键微调 <span>·</span> 每一步都可以撤销</div><div class="soundtrack"><button class="play" data-action="play" aria-label="${playing?'暂停':'试听'}原创声景">${ic(playing?'pause':'play')}</button><div class="track-info"><small>这次相遇的 BGM</small><strong>${e(song().title)} <span>· ${e(song().artist)}</span></strong></div><div class="wave ${playing?'playing':''}">${Array.from({length:17},(_,i)=>`<i style="--h:${10+(i*7%21)}px;--d:${i*.08}s"></i>`).join('')}</div>${button('music','换一首','text-btn')}</div></div>
 <aside class="editor-panel"><div class="editor-tabs" role="group" aria-label="编辑工具">${[['scene','场景'],['tune','调一调'],['together','一起出演']].map(([id,label])=>button('tab',label,tab===id?'active':'',`aria-pressed="${tab===id}" data-value="${id}"`)).join('')}</div><div class="editor-body">${tab==='scene'?sceneControls():tab==='tune'?tuneControls():togetherControls()}</div><div class="editor-bottom"><div class="save-status"><i></i>${e(statusLabel())}</div>${primaryAction()}${invite?'':remote?button('save-local-copy',`${ic('bookmark')}收进我的作品`,'secondary save-local'):button('export-solo',`${ic('download')}保存我的图片`,'secondary save-local')}${remote||invite?button('return-draft','返回我的私密草稿','text-btn return-draft'):''}${storageFailed?'<p class="danger">本机存储不足，请导出后再关闭</p>':'<p class="privacy-small">你的分身不会替别人做决定</p>'}</div></aside></section>`}</main><footer class="app-footer"><span>MUSIC SPACE <span class="footer-dot">·</span> MAKE ROOM FOR SOMEONE</span><span>照片和分身合成创作 ${button('about','关于与隐私','text-btn')}</span></footer>`;
 bindCanvas(); mountVisual();
}
function visualState(){let host=currentHost(),guest=currentGuest();const appearance=avatarEditing&&avatarDraft?avatarDraft.avatar:draft.avatar;if(!isGuest())host={...host,avatar:appearance,transform:draft.transform};if(isGuest()&&guest)guest={...guest,avatar:appearance,transform:draft.transform};return {scene:{...draft.scene,background:bgFor(draft.scene)},host,guest,playing,bpm:song().bpm,reducedMotion:window.matchMedia?.('(prefers-reduced-motion: reduce)').matches||false};}
function mountVisual(){const stage=$('#artboard');if(stage)stage.classList.toggle('photo-mode',draft.scene.kind==='photo');if(!stage){toon?.update({...visualState(),playing:false});refreshPortraits();return;}if(toonFailed){stage.dataset.renderMode='lite';return;}try{if(!toonLayer){toonLayer=document.createElement('div');toonLayer.className='toon-layer';toonLayer.setAttribute('aria-hidden','true');toonLayer.addEventListener('toonerror',()=>{toonFailed=true;stage.dataset.renderMode='lite';stage.classList.remove('toon-ready');toast('3D 预览暂时不可用，已保留编辑并切换轻量画面',true);});}stage.prepend(toonLayer);if(!toon)toon=mountToonScene(toonLayer,visualState());else toon.update(visualState());stage.classList.add('toon-ready');stage.dataset.renderMode='3d';syncHitAreas();refreshPortraits();}catch(error){console.warn('3D preview unavailable',error.message);toonFailed=true;toon?.dispose();toon=null;toonLayer?.remove();stage.dataset.renderMode='lite';}}
function syncHitAreas(){if(!toon?.getBounds)return;const bounds=toon.getBounds(),mine=isGuest()?'guest':'host';for(const el of document.querySelectorAll('#artboard .person')){const slot=el.dataset.person==='me'?mine:mine==='host'?'guest':'host';if(bounds[slot])el.style.height=bounds[slot].height+'%';}}
function updateVisual(){if(toon&&!toonFailed)try{toon.update(visualState());syncHitAreas();}catch{}}
function portraitFor(a,fullBody=true){if(!toon?.portrait)return null;const key=JSON.stringify([{...a,pose:'listen'},fullBody]);if(portraits.has(key))return portraits.get(key);try{const url=toon.portrait({...a,pose:'listen'},{fullBody,size:320});if(typeof url==='string'){if(portraits.size>=80)portraits.delete(portraits.keys().next().value);portraits.set(key,url);return url;}}catch{}return null;}
function identityPortrait(value){const a=safeAvatar(value);return `<span class="identity-portrait" data-avatar-portrait="${e(JSON.stringify(a))}">${avatarSVG(a)}</span>`;}
function refreshPortraits(){const appearance=avatarEditing&&avatarDraft?avatarDraft.avatar:draft.avatar;
 for(const el of document.querySelectorAll('[data-template],[data-part-key]')){let variant,fullBody=true;if(el.dataset.template!==undefined){variant={...TEMPLATES[Number(el.dataset.template)].avatar,skin:appearance.skin};}else{const key=el.dataset.partKey,value=['accessory','expression','pose'].includes(key)?el.dataset.partValue:Number(el.dataset.partValue);variant={...appearance,[key]:value};fullBody=!['hair','eyewear','expression'].includes(key);}const url=portraitFor(variant,fullBody);if(url)el.innerHTML=`<img src="${url}" alt=""/>`;}
 const url=portraitFor(appearance);if(url){const el=$('.avatar-pedestal');if(el){const child=el.querySelector('svg,img');const img=new Image();img.src=url;img.alt='';img.className='toon-portrait';child?.replaceWith(img);}}
 for(const el of document.querySelectorAll('[data-avatar-portrait]')){try{const a=safeAvatar(JSON.parse(el.dataset.avatarPortrait)),url=portraitFor(a,true);if(url)el.innerHTML=`<img src="${url}" alt=""/>`;}catch{}}
 const mini=$('.profile-mini'),face=portraitFor(profile?.avatar||draft.avatar,false);if(mini&&face)mini.innerHTML=`<img class="toon-portrait" src="${face}" alt=""/>`;
}
function personMarkup(person,own=false){const t=person.transform;return `<div class="person ${own?'editable':''}" ${own?'tabindex="0" role="button" aria-label="移动我的分身：方向键微调位置"':''} style="left:${t.x}%;top:${t.y}%;width:${32*t.scale}%;transform:translate(-50%,-100%) rotate(${t.rotation}deg);z-index:${Math.round(t.y)}" data-person="${own?'me':'other'}">${avatarSVG(person.avatar)}<span class="person-name">${e(person.name)}${own?' · 我':''}</span></div>`;}
function scenePeople(){const host=currentHost(),guest=currentGuest();let result=personMarkup(host,!isGuest()&&!remote);if(remote&&remote.role==='host')result=personMarkup({...host,avatar:draft.avatar,transform:draft.transform},true);if(guest)result+=personMarkup(remote?.role==='guest'?{...guest,avatar:draft.avatar,transform:draft.transform}:guest,isGuest());else result+=`<button class="empty-spot" data-action="invite" style="left:69%;top:72%" aria-label="邀请朋友加入空着的位置"><span class="ghost-avatar">${ic('plus')}</span><strong>这里，留给你</strong></button>`;return result;}
function sceneControls(){return `<div class="panel-heading"><span class="section-no">01 /</span><h2>为这一刻，选个片场。</h2><p>真实 3D 夜景，或你自己的照片。</p></div><div class="scene-options">${scenes.map(s=>`<button class="scene-option ${draft.scene.id===s.id?'selected':''}" data-action="scene" data-value="${s.id}" ${invite||remote?'disabled':''}><img src="${bgFor({kind:'builtin',id:s.id})}" alt="${s.name}原创虚构场景"/><span><strong>${s.name}</strong><small>${s.hint}</small></span><span class="selection-check">${ic('check')}</span></button>`).join('')}</div><div class="or-rule"><span>或者，让生活成为舞台</span></div><label class="upload ${invite||remote?'disabled':''}">${ic('photo')}<span><strong>用自己的照片</strong><small>JPG / PNG / WebP · 最大 15 MB</small></span><input id="photo-input" type="file" accept="image/jpeg,image/png,image/webp" ${invite||remote?'disabled':''}/></label><p class="helper">照片在本机去除元数据。创建邀请前不会上传。</p>${draft.scene.id==='fan-stage'?'<p class="note">「月白」是原创虚构音乐人。同台仅为想象创作，不代表真实艺人参与或代言；邀请真实朋友时会替换此角色。</p>':''}`;}
function tuneControls(){return `<div class="panel-heading"><span class="section-no">02 /</span><h2>像你，也听你的。</h2><p>把每一个细节，调成这一刻的心情。</p></div><label class="field">作品名字<input id="title" maxlength="24" value="${e(draft.title)}" ${invite||remote?'disabled':''}/></label><label class="field">留一句话<textarea id="caption" maxlength="72" rows="2" ${invite||remote?'disabled':''}>${e(draft.caption)}</textarea></label><div class="mobile-poses"><span class="field">出演方式</span><div class="segmented">${POSES.map(([id,label])=>button('pose',label,draft.avatar.pose===id?'active':'',`data-value="${id}" aria-pressed="${draft.avatar.pose===id}"`)).join('')}</div></div><div class="range-row"><label for="scale">分身大小</label><output>${Math.round(draft.transform.scale*100)}%</output></div><input id="scale" type="range" min="0.55" max="1.35" step=".01" value="${draft.transform.scale}"/><div class="range-row"><label for="rotation">身体倾斜</label><output>${draft.transform.rotation}°</output></div><input id="rotation" type="range" min="-20" max="20" step="1" value="${draft.transform.rotation}"/><div class="range-row"><label for="position-y">远近位置</label><output>${Math.round(draft.transform.y)}%</output></div><input id="position-y" type="range" min="45" max="93" value="${draft.transform.y}"/><div class="mini-actions">${button('reset-position',`${ic('refresh')}回到初始位置`,'secondary')}</div><p class="note">人物接触阴影随位置和比例移动。自己的照片不会自动识别遮挡，你可以手动调整构图。</p>`;}
function togetherControls(){
 if(invite)return `<div class="panel-heading"><span class="section-no">03 /</span><h2>我这样加入你。</h2><p>${e(invite.host.name)} 留下的场景，由你带来另一半。</p></div><div class="invitation-note"><span>TA 想对你说</span><p>“${e(invite.caption)}”</p></div><label class="field">你的回应<textarea id="response" maxlength="72" rows="3" placeholder="比如：副歌的这一句，我来唱。">${e(draft.response||'')}</textarea></label><label class="consent-check"><input id="join-consent" type="checkbox" ${draft.joinConsent?'checked':''}/><span>我愿意将自己的分身和回应加入这张作品，让邀请者查看。共同保存另行确认。</span></label><p class="note">加入后仍可调整或退出。只有双方都同意，才能保存共同作品。</p>`;
 if(remote)return `<div class="panel-heading"><span class="section-no">03 /</span><h2>${remote.guest?'两个人，才完整。':'位置留好了。'}</h2><p>${remote.guest?'每一个加入，都值得被认真回应。':'把邀请交给那个你想一起听歌的人。'}</p></div><div class="coauthors">${[remote.host,remote.guest].filter(Boolean).map(p=>`<div>${identityPortrait(p.avatar)}<strong>${e(p.name)}</strong><small>${p.id===session?.user?.id?'我':'共同出演'}</small></div>`).join('')}${remote.guest?'':'<div class="await-avatar">＋<small>等一个朋友</small></div>'}</div>${remote.role==='guest'?`<label class="field">你的回应<textarea id="response" maxlength="72" rows="2">${e(draft.response||'')}</textarea></label>`:''}${remote.guest?`<div class="invitation-note"><span>${e(remote.guest.name)} 的回应</span><p>“${e(remote.guest.response||'一起听这首歌。')}”</p></div>`:''}${remote.status==='pending'&&remote.role==='host'?`<div class="decision-actions">${button('accept',`${ic('check')}喜欢这个版本`,'primary')}${button('reject','请朋友再调整一下','text-btn')}</div>`:''}${remote.status==='accepted'?`<label class="consent-check"><input id="share-consent" type="checkbox" ${remote.consents[remote.role]?'checked':''}/><span>我同意双方保存当前版本的合成图片。保存后的副本无法远程撤回。</span></label><div class="consent-status"><span>${remote.consents.host?'✓':'○'} ${e(remote.host.name)} 同意保存</span><span>${remote.consents.guest?'✓':'○'} ${e(remote.guest?.name)} 同意保存</span></div>`:''}${remote.role==='host'?button('copy-invite',`${ic('link')}${remote.inviteActive&&inviteLink?'复制邀请链接':'重新生成邀请'}`,'secondary',remote.guest?'disabled':''):button('leave','退出这张共同作品','text-btn danger')}${remote.role==='host'&&remote.inviteActive?button('revoke','关闭邀请入口','text-btn danger'):''}<p class="note">邀请链接只用于这张作品，不会公开你的其它草稿。转发链接的人也可以看到邀请内容。</p>`;
 return `<div class="panel-heading"><span class="section-no">03 /</span><h2>给你，留个位置。</h2><p>不是点赞，而是带着自己的样子加入。</p></div><div class="together-illustration">${identityPortrait(draft.avatar)}<span class="dashed-seat">＋</span><i>see you here ↗</i></div><ol class="steps"><li><b>01</b><span><strong>先留下你的那一半</strong><small>场景、分身，还有想分享的歌。</small></span></li><li><b>02</b><span><strong>朋友决定怎样加入</strong><small>自己的形象、动作和一句回应。</small></span></li><li><b>03</b><span><strong>两个人点头，收好这一刻</strong><small>共同确认之后，保存双人作品。</small></span></li></ol>`;}
function primaryAction(){if(invite)return button('join',`带着我的分身加入 ${ic('arrow')}`,'primary',busy?'disabled':'');if(remote&&isDirty())return button('update-remote','保存我的调整','primary',busy?'disabled':'');if(remote?.exportEligible)return button('export-joint',`${ic('download')}保存我们的作品`,'primary',busy?'disabled':'');if(remote&&remote.role==='guest')return button('update-remote','保存我的调整','primary',busy?'disabled':'');if(remote)return button('refresh',`${ic('refresh')}查看朋友的回应`,'primary',busy?'disabled':'');return button('invite',`给朋友留个位置 ${ic('arrow')}`,'primary',busy?'disabled':'');}
function worksPage(){return `<section class="studio-heading"><div><div class="eyebrow">LITTLE MOMENTS, KEPT FOREVER</div><h1>我们留下的，不止照片。</h1><p>私密草稿与共同作品，都在这里慢慢积攒。</p></div>${button('new',`${ic('plus')}新的相遇`,'primary')}</section><div class="works-grid">${works.map(w=>`<article class="work-card"><button data-action="open-work" data-value="${e(w.id)}"><div class="work-image" style="background-image:url('${e(w.preview||bgFor(w.scene))}')">${w.preview?'':`<div class="work-avatar">${identityPortrait(w.avatar||DEFAULT_AVATAR)}</div>`}<span class="work-tag">${w.remoteId?'双人共创':'本机私藏'}</span></div><div class="work-details"><small>${new Date(w.savedAt).toLocaleDateString('zh-CN')} / ${e(SONGS.find(s=>s.id===w.songId)?.title||'原创声景')}</small><h2>${e(w.title)}</h2><p>${e(w.caption)}</p></div></button><button data-action="delete-work" data-value="${e(w.id)}" class="icon-btn delete-work" aria-label="删除本机作品 ${e(w.title)}">${ic('trash')}</button></article>`).join('')}<button class="new-work" data-action="new"><span>＋</span><strong>下次见面，听什么？</strong><small>从新的场景开始</small></button></div>`;}
function bindCanvas(){const el=$('[data-person="me"]');if(!el)return;let drag=null;el.addEventListener('pointerdown',event=>{if(event.button!==0)return;const r=$('#artboard').getBoundingClientRect();drag={start:clone(draft),x:event.clientX,y:event.clientY,r,moved:false};el.setPointerCapture(event.pointerId);el.classList.add('dragging');event.preventDefault();});el.addEventListener('pointermove',event=>{if(!drag)return;const dx=(event.clientX-drag.x)/drag.r.width*100,dy=(event.clientY-drag.y)/drag.r.height*100;if(Math.abs(dx)+Math.abs(dy)>.3)drag.moved=true;draft.transform.x=Math.round(clamp(drag.start.transform.x+dx,14,86)*10)/10;draft.transform.y=Math.round(clamp(drag.start.transform.y+dy,45,94)*10)/10;el.style.left=draft.transform.x+'%';el.style.top=draft.transform.y+'%';el.style.zIndex=Math.round(draft.transform.y);updateVisual();});const end=()=>{if(!drag)return;if(drag.moved){history.push(drag.start);redo=[];persist();}drag=null;el.classList.remove('dragging');};el.addEventListener('pointerup',()=>{end();render();});el.addEventListener('pointercancel',()=>{if(drag)draft=drag.start;drag=null;render();});el.addEventListener('keydown',event=>{const dirs={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(!dirs[event.key])return;event.preventDefault();const m=event.shiftKey?5:1;commit(d=>{d.transform.x=clamp(d.transform.x+dirs[event.key][0]*m,14,86);d.transform.y=clamp(d.transform.y+dirs[event.key][1]*m,45,94);});$('[data-person="me"]')?.focus();});}
function openModal(html,cls=''){
 const updating=modal.open&&cls.includes('avatar-drawer')&&modal.className.includes('avatar-drawer');
 const focused=updating?document.activeElement:null;const focusData=focused?.dataset?{action:focused.dataset.action,key:focused.dataset.key,value:focused.dataset.value}:null;
 if(!modal.open)lastFocus=document.activeElement;modal.className=cls;modal.innerHTML=`<button class="modal-close icon-btn" data-action="close-modal" aria-label="${cls.includes('avatar-drawer')?'取消分身修改':'关闭'}">${ic('close')}</button>${html}`;
 const heading=modal.querySelector('h2');if(heading){heading.id='modal-title';modal.setAttribute('aria-labelledby','modal-title');}else{modal.removeAttribute('aria-labelledby');modal.setAttribute('aria-label','画面预览');}
 if(!modal.open)modal.showModal();refreshPortraits();
 setTimeout(()=>{let target;if(updating&&focusData?.action){target=[...modal.querySelectorAll('[data-action]')].find(el=>el.dataset.action===focusData.action&&el.dataset.key===focusData.key&&el.dataset.value===focusData.value);}if(!target)target=cls.includes('avatar-drawer')?modal.querySelector('[data-action="avatar-category"].active'):modal.querySelector('input,button:not(.modal-close),textarea');target?.focus({preventScroll:true});},10);
}
function closeModal(){const wasEditing=avatarEditing;avatarEditing=false;document.body.classList.remove('wardrobe-open');modal.close();modal.innerHTML='';if(wasEditing){render();updateVisual();}if(lastFocus?.isConnected)lastFocus.focus();else if(wasEditing)$('[data-action=avatar]')?.focus();}
modal.addEventListener('click',ev=>{if(ev.target===modal){const r=modal.getBoundingClientRect();if(ev.clientX<r.left||ev.clientX>r.right||ev.clientY<r.top||ev.clientY>r.bottom)closeModal();}});
modal.addEventListener('cancel',ev=>{ev.preventDefault();closeModal();});
let avatarDraft=null;
function avatarDialog(){avatarDraft={name:profile?.name||'',avatar:safeAvatar(draft.avatar)};avatarEditing=true;avatarCategory='presets';document.body.classList.add('wardrobe-open');renderAvatarDialog(true);}
const wardrobeTabs=[['presets','搭配'],['hair','发型'],['eyewear','眼镜'],['top','上装'],['bottom','下装'],['shoes','鞋履'],['accessory','配件'],['expression','表情'],['pose','动作'],['colors','配色']];
function wardrobeOptions(){const a=avatarDraft.avatar,key=avatarCategory;
 if(key==='presets')return `<div class="wardrobe-section-title"><h3>从一套搭配开始。</h3><p>名字和肤色不变，每一件都能单独换。</p></div><div class="component-grid presets-grid">${TEMPLATES.map((t,i)=>`<button class="component-card ${['hair','top','bottom','shoes','eyewear'].every(k=>a[k]===t.avatar[k])?'selected':''}" data-action="avatar-template" data-value="${i}"><span class="component-portrait" data-template="${i}">${avatarSVG({...t.avatar,skin:a.skin})}</span><strong>${t.name}<small>${t.english}</small></strong><span class="component-detail">${t.note}</span></button>`).join('')}</div>`;
 if(key==='colors')return `<div class="wardrobe-section-title"><h3>你的配色，没有标准答案。</h3><p>一件一件调，不会改掉其它部件。</p></div>${swatches('skin','肤色',SKINS,a.skin)}${swatches('hairColor','发色',HAIRS,a.hairColor)}${swatches('topColor','上装颜色',GARMENT_COLORS,a.topColor)}${swatches('bottomColor','下装颜色',GARMENT_COLORS,a.bottomColor)}${swatches('shoeColor','鞋履颜色',GARMENT_COLORS,a.shoeColor)}`;
 const entries=key==='pose'?POSES.map(([id,label])=>[id,label,'']):(COMPONENTS[key]||[]).map((entry,i)=>['accessory','expression'].includes(key)?entry:[i,...entry]);
 const title=wardrobeTabs.find(t=>t[0]===key)?.[1]||'';
 return `<div class="wardrobe-section-title"><h3>只换${title}，其它由你保留。</h3><p>${entries.length} 种选择 · 可与所有已选部件自由组合</p></div><div class="component-grid ${['hair','eyewear','expression'].includes(key)?'head-parts':''}">${entries.map(([value,label,english])=>{const variant={...a,[key]:value};return `<button class="component-card ${a[key]===value?'selected':''}" data-action="avatar-option" data-key="${key}" data-value="${value}" aria-pressed="${a[key]===value}"><span class="component-portrait" data-part-key="${key}" data-part-value="${value}">${avatarSVG(variant)}</span><strong>${label}<small>${english}</small></strong></button>`;}).join('')}</div>`;
}
function renderAvatarDialog(resetScroll=false){const scroll=resetScroll?0:$('.wardrobe-content')?.scrollTop||0;
 openModal(`<div class="wardrobe-head"><span class="modal-kicker">SPACE / LOOK LAB</span><h2>你的形象，你说了算。</h2><p>搭配是起点。每一件，都可以自由组合。</p></div><label class="wardrobe-name"><span>署名</span><input id="avatar-name" maxlength="18" placeholder="你的名字" value="${e(avatarDraft.name)}" autocomplete="nickname"/></label><div class="wardrobe-tabs" role="group" aria-label="选择造型部件">${wardrobeTabs.map(([id,label])=>button('avatar-category',label,avatarCategory===id?'active':'',`data-value="${id}" aria-pressed="${avatarCategory===id}"`)).join('')}</div><div class="wardrobe-content">${wardrobeOptions()}</div><div class="wardrobe-footer"><span>当前为预览 · 保存后才更新你的分身</span><div>${button('close-modal','取消','secondary')}${button('save-avatar',`保存分身 ${ic('check')}`,'primary')}</div></div>`,'avatar-modal avatar-drawer');
 const content=$('.wardrobe-content');if(content)content.scrollTop=scroll;refreshPortraits();updateVisual();
 if(toonFailed){const el=$('[data-person="me"]');const svg=el?.querySelector('svg');if(svg)svg.outerHTML=avatarSVG(avatarDraft.avatar);}
}
function swatches(key,label,colors,selected){return `<div class="field"><span>${label}</span><div class="swatches">${colors.map((c,i)=>button('avatar-option',selected===i?ic('check'):'',selected===i?'selected':'',`style="--swatch:${c}" data-key="${key}" data-value="${i}" aria-label="${label} ${i+1}" aria-pressed="${selected===i}"`)).join('')}</div></div>`;}
function musicDialog(){openModal(`<div class="modal-kicker">A SONG TO SHARE</div><h2>把心情放进这首歌。</h2><p class="modal-intro">三段原创合成声景，点击试听 24 秒。没有商业歌曲录音。</p><div class="music-options">${SONGS.map(s=>`<button data-action="choose-song" data-value="${s.id}" class="music-option ${draft.songId===s.id?'selected':''}" ${invite||remote?'disabled':''}><span class="record" style="--record:${s.color}"><i></i></span><span><small>${s.tag}</small><strong>${s.title}</strong><p>${s.mood}</p></span><span>${draft.songId===s.id?ic('check'):ic('arrow')}</span></button>`).join('')}</div><p class="note">音乐影响这次相遇的气氛与动作建议，分身的长相仍由你决定。</p>`);}
function aboutDialog(){openModal(`<div class="modal-kicker">A SMALL, HONEST SPACE</div><h2>亲近，也有边界。</h2><div class="about-copy"><p>Space 是一个以分身为身份的双人创作工作室。场景与原创虚构音乐人由创作生成，不是真实艺人参与、真实合照或代言。</p><h3>从私密草稿，到两个人的作品</h3><p>普通草稿、上传照片和分身先保存在当前浏览器。照片在本机重绘，移除原始元数据。只有你主动创建邀请，当前作品才会传到共创服务。</p><p>任何持有邀请链接的人都能看见邀请中的照片、你的分身、昵称和留言。链接不暴露你的其它作品，可随时关闭入口。</p><p>朋友用自己的身份加入。你确认这个版本后，双方还要分别同意保存，才能导出共同作品。任何一方修改都会重新确认；已经下载的副本不能远程撤回。</p><h3>设备和连接</h3><p>匿名身份凭证只保存在本机，尚无账号找回。清除浏览器数据会失去访问权。本机作品不自动同步；请及时导出。已载入的页面离线仍可继续创作，双人邀请与共同保存需要连接共创服务。</p><p>画布使用手工可控的位置、姿态与阴影，不声称自动识别照片遮挡。音乐试听是本项目程序生成的原创声景。</p></div>${button('close-modal','知道了','primary')}`);}
async function withBusy(fn){if(busy)return;const generation=routeGeneration,workId=remote?.id,joiningToken=invite?inviteToken:null;busy=true;document.body.classList.add('busy');try{await fn();}catch(err){if(generation!==routeGeneration)return;if(err.status===409&&err.code==='REVISION_CONFLICT'){if(joiningToken&&inviteToken===joiningToken&&invite){toast('邀请内容刚刚更新。你的造型和回应仍在，请查看新画面后重新勾选同意。',true);draft.joinConsent=false;persist();await refreshInvitation(joiningToken,generation).catch(()=>{});}else if(remote?.id===workId){toast('对方刚刚修改了作品。你的调整仍在，请查看新版本后再保存。',true);await refreshRemote(true).catch(()=>{});}}else if(err.status===401){toast('本机身份已失效。草稿已保留；请重新建立身份，旧共同作品不会自动找回。',true);openModal(`<h2>身份需要重新建立</h2><p class="modal-intro">草稿和分身还在这台设备。旧身份对应的共同作品无法自动找回。</p>${button('reset-session','保留草稿，建立新身份','primary')}`);}else toast(err.message||'没有完成，请重试',true);}finally{busy=false;document.body.classList.remove('busy');render();}}
async function ensureSession(){if(!profile){avatarDialog();throw Error('先创建一个属于你的分身，再邀请朋友');}if(session){await request('/session',{token:session.token});return session;}const r=await request('/session',{method:'POST',body:profile});session=r;try{localStorage.setItem(SESSION_KEY,JSON.stringify(session));}catch{session=null;throw Error('浏览器无法保存新的身份，请先释放本机存储空间再邀请。草稿仍在。');}persist();return r;}
async function syncProfile(){if(!session)return;const fresh=await request('/session',{token:session.token});session.user=fresh.user;const r=await request('/profile',{method:'PUT',token:session.token,body:{...profile,revision:session.user.revision}});session.user=r.user;localStorage.setItem(SESSION_KEY,JSON.stringify(session));persist();}
function remoteDraft(c,preserve=false){remote=c;inviteLink=c.inviteActive?(inviteLinks[c.id]||''):'';const me=c[c.role];if(!preserve)draft={...newDraft(me.avatar),id:c.id,title:c.title,caption:c.caption,scene:c.scene,songId:c.songId,avatar:safeAvatar(me.avatar),transform:clone(me.transform),response:me.response||''};persist();}
async function loadPhoto(scene,token,revision=''){const generation=routeGeneration;const cacheKey=scene.photoUrl+'@'+revision;if(scene.kind!=='photo'||scene.dataUrl)return;if(cacheKey===photoKey)return;const url=await photoBlob(scene.photoUrl,token);if(generation!==routeGeneration){URL.revokeObjectURL(url);return;}if(photoURL)URL.revokeObjectURL(photoURL);photoURL=url;photoKey=cacheKey;}
async function refreshInvitation(token=inviteToken,generation=routeGeneration){const r=await request(`/invites/${encodeURIComponent(token)}`);if(generation!==routeGeneration||!invite||inviteToken!==token)return;invite=r.preview;draft={...draft,title:invite.title,caption:invite.caption,scene:invite.scene,songId:invite.songId,joinConsent:false};persist();await loadPhoto(invite.scene,null,invite.revision);if(generation===routeGeneration&&inviteToken===token)render();}
function onWorkRoute(generation,id){return generation===routeGeneration&&remote?.id===id;}
async function refreshRemote(preserve=false){if(!remote||!session)return;const id=remote.id,generation=routeGeneration;const {composition:c}=await request(`/compositions/${id}`,{token:session.token});if(generation!==routeGeneration||remote?.id!==id)return;remoteDraft(c,preserve);await loadPhoto(c.scene,session.token,c.contentRevision);rememberRemote(c);render();}
function rememberRemote(c){const w={id:c.id,remoteId:c.id,title:c.title,caption:c.caption,scene:c.scene.kind==='builtin'?c.scene:{kind:'photo'},songId:c.songId,avatar:c.host.avatar,savedAt:c.updatedAt};const i=works.findIndex(x=>x.id===c.id);if(i<0)works.unshift(w);else works[i]={...works[i],...w};persist();}
async function createInvitation(){if(!profile){avatarDialog();return;}if(connected===false){openModal(`<div class="modal-kicker">YOUR DRAFT IS SAFE</div><h2>先把这一刻留在本机。</h2><p class="modal-intro">当前是静态创作模式。跨设备邀请需要共创服务；本机创作、分身调整与单人导出都能继续。</p><div class="modal-actions">${button('close-modal','继续创作','secondary')}${button('export-solo','保存我的图片','primary')}</div>`);return;}if(remote){tab='together';render();return;}openModal(`<div class="modal-kicker">SAVE A PLACE FOR SOMEONE</div><h2>这里，留给谁都不一样。</h2><p class="modal-intro">创建邀请会上传当前场景或照片、你的分身、昵称与留言。任何拿到链接的人都能预览这张邀请。</p><div class="invite-summary"><span class="mini-avatar">${identityPortrait(draft.avatar)}</span><div><strong>${e(draft.title)}</strong><p>${e(draft.caption)}</p><small>♫ ${e(song().title)}</small></div></div><p class="note">朋友用自己的分身加入。加入不代表允许导出；共同保存仍需双方分别同意。</p><div class="modal-actions">${button('close-modal','再调一调','secondary')}${button('confirm-invite',`创建私密邀请 ${ic('arrow')}`,'primary')}</div>`);}
async function confirmInvitation(){
 const generation=routeGeneration,reviewed=clone(draft),existing=remote?clone(remote):null;
 await ensureSession();if(generation!==routeGeneration)return;let c=existing;
 if(!c){const result=await request('/compositions',{method:'POST',token:session.token,body:{title:reviewed.title,caption:reviewed.caption,scene:reviewed.scene,songId:reviewed.songId,avatar:reviewed.avatar,transform:reviewed.transform}});c=result.composition;rememberRemote(c);if(generation===routeGeneration){localDraft=reviewed;remoteDraft(c);history=[];redo=[];historyReplace(`#work=${c.id}`);await loadPhoto(c.scene,session.token,c.contentRevision);}}
 const r=await request(`/compositions/${c.id}/invite`,{method:'POST',token:session.token,body:{revision:c.revision}});inviteLinks[c.id]=`${location.href.split('#')[0]}#invite=${encodeURIComponent(r.inviteToken)}`;rememberRemote(r.composition);
 if(generation!==routeGeneration){toast('邀请已创建，可以从我的作品继续');return;}
 remoteDraft(r.composition);inviteToken=r.inviteToken;inviteLink=`${location.href.split('#')[0]}#invite=${encodeURIComponent(inviteToken)}`;inviteLinks[c.id]=inviteLink;persist();tab='together';render();inviteDialog();
}
function inviteDialog(){openModal(`<div class="modal-kicker">ONE LINK, ONE LITTLE WORLD</div><h2>把空着的位置，交给 TA。</h2><p class="modal-intro">朋友在另一台设备打开，用自己的分身回应。别公开转发包含私人照片的邀请。</p><label class="field">邀请链接<input id="invite-link" readonly value="${e(inviteLink)}"/></label><div class="modal-actions">${button('close-modal','等 TA 入镜','secondary')}${button('copy-link',`${ic('link')}复制链接`,'primary')}</div><p class="modal-fine">${location.hostname==='127.0.0.1'||location.hostname==='localhost'?'当前为本机地址。其他设备需使用同一网络可访问的服务地址。':'邀请仅属于这一张作品，你可以随时关闭入口。'}</p>`);}
async function joinInvitation(){
 if(!profile){avatarDialog();return;}if(!invite)return;if(!draft.joinConsent){toast('请先勾选同意，将你的分身和回应加入这张作品');tab='together';render();return;}
 const generation=routeGeneration,token=inviteToken,id=invite.id,body=clone({revision:invite.revision,response:draft.response||'',transform:draft.transform,avatar:draft.avatar,consent:true});
 await ensureSession();if(generation!==routeGeneration||inviteToken!==token||invite?.id!==id)return;
 const {composition:c}=await request(`/invites/${token}/join`,{method:'POST',token:session.token,body});
 if(generation!==routeGeneration||inviteToken!==token||invite?.id!==id){rememberRemote(c);return;}
 invite=null;remoteDraft(c);rememberRemote(c);history=[];redo=[];historyReplace(`#work=${c.id}`);tab='together';render();toast('你入镜了。邀请者会看到你的回应。');
}
function historyReplace(hash){window.history.replaceState(null,'',`${location.pathname}${location.search}${hash}`);}
async function updateRemote(){if(!isDirty()){toast('当前版本已经保存');return;}const generation=routeGeneration,id=remote.id,body=clone({revision:remote.revision,avatar:draft.avatar,transform:draft.transform,...(remote.role==='guest'?{response:draft.response??remote.guest?.response??''}:{})});const {composition:c}=await request(`/compositions/${id}`,{method:'PATCH',token:session.token,body});if(!onWorkRoute(generation,id))return;remoteDraft(c);rememberRemote(c);render();toast('调整已保存。双方需重新确认这个版本。');}
async function decision(accept){if(!requireClean())return;const generation=routeGeneration,id=remote.id;const {composition:c}=await request(`/compositions/${id}/decision`,{method:'POST',token:session.token,body:{revision:remote.revision,accept}});if(!onWorkRoute(generation,id))return;remoteDraft(c);render();toast(accept?'这一版确认了。双方同意后就能保存。':'已留给朋友继续调整。');}
async function consent(value){if(!requireClean()){render();return;}const generation=routeGeneration,id=remote.id;const {composition:c}=await request(`/compositions/${id}/consent`,{method:'POST',token:session.token,body:{revision:remote.revision,consent:value}});if(!onWorkRoute(generation,id))return;remoteDraft(c);render();toast(c.exportEligible?'两个人都点头了，可以保存共同作品。':value?'已记下你的同意，等对方确认。':'已撤回后续导出的许可。');}
async function saveLocal(){if(remote){await updateRemote();return;}const item={...clone(draft),savedAt:new Date().toISOString()};const i=works.findIndex(w=>w.id===item.id);if(i<0)works.unshift(item);else works[i]=item;if(persist())toast('已收进「我的作品」，仅保存在这台设备');render();}
async function makeExport(joint=false){if(!joint&&(invite||remote)){toast('共同场景须由双方确认后保存',true);return;}if(joint&&!requireClean())return;const generation=routeGeneration;let c;if(joint){const r=await request(`/compositions/${remote.id}/export`,{token:session.token});c=r.composition||r;if(generation!==routeGeneration)return;await loadPhoto(c.scene,session.token,c.contentRevision);}else c={...clone(draft),host:{name:profile?.name||'我',avatar:draft.avatar,transform:draft.transform},guest:draft.scene.id==='fan-stage'?currentGuest():null};if(generation!==routeGeneration)return;let sceneCapture=null;if(toon&&!toonFailed){toon.update({scene:{...c.scene,background:bgFor(c.scene)},host:c.host,guest:c.guest,playing:false,bpm:song().bpm,reducedMotion:true});await toon.ready;if(generation!==routeGeneration){updateVisual();return;}sceneCapture=toon.capture({width:1440,height:1920});updateVisual();}const blob=await exportImage({...c,background:bgFor(c.scene),sceneCapture});if(generation!==routeGeneration)return;const url=URL.createObjectURL(blob);openModal(`<div class="modal-kicker">KEEP THIS LITTLE MOMENT</div><h2>${joint?'属于我们的这一刻。':'这一刻，收好了。'}</h2><div class="export-preview"><img src="${url}" alt="导出的 Music Space 作品预览"/></div><a class="primary download-link" href="${url}" download="space-${Date.now()}.png">${ic('download')}下载 PNG 图片</a><p class="modal-fine">1440 × 1920 · 手机可长按图片保存</p>`,'export-modal');modal.addEventListener('close',()=>URL.revokeObjectURL(url),{once:true});}
function newWork(){routeGeneration++;{const w={...clone(remote||invite?localDraft:draft),savedAt:new Date().toISOString()};const i=works.findIndex(x=>x.id===w.id);if(i<0)works.unshift(w);else works[i]=w;}remote=null;invite=null;inviteToken=null;inviteLink='';draft=newDraft(profile?.avatar);history=[];redo=[];tab='scene';view='studio';historyReplace('');persist();render();}
async function openRoute(){
 const generation=++routeGeneration,hash=location.hash.slice(1);routeLoading=hash.startsWith('invite=')||hash.startsWith('work=');if(routeLoading&&!remote&&!invite)localDraft=clone(draft);if(modal.open&&(routeLoading||remote||invite))closeModal();render();
 try{
  if(hash.startsWith('invite=')){
   inviteToken=decodeURIComponent(hash.slice(7));
   const r=await request(`/invites/${encodeURIComponent(inviteToken)}`);if(generation!==routeGeneration)return;
   if(r.preview.host.id===session?.user?.id){historyReplace(`#work=${r.preview.id}`);await openRoute();return;}
   history=[];redo=[];invite=r.preview;remote=null;
   draft={...newDraft(profile?.avatar),title:invite.title,caption:invite.caption,scene:invite.scene,songId:invite.songId,transform:{x:66,y:81,scale:1,rotation:0}};
   await loadPhoto(invite.scene,null,invite.revision);if(generation!==routeGeneration)return;tab='together';view='studio';
  }else if(hash.startsWith('work=')){
   if(!session)throw Error('这张共同作品需要原来的浏览器身份。昵称无法恢复旧身份。');
   const {composition:c}=await request(`/compositions/${encodeURIComponent(hash.slice(5))}`,{token:session.token});if(generation!==routeGeneration)return;
   const pending=pendingEdits[c.id];invite=null;remoteDraft(c);
   if(pending?.avatar&&pending?.transform){draft.avatar=pending.avatar;draft.transform=pending.transform;draft.response=pending.response||'';persist();toast('已恢复这张作品上未保存的调整');}
   history=[];redo=[];await loadPhoto(c.scene,session.token,c.contentRevision);if(generation!==routeGeneration)return;view='studio';tab='together';
  }else if(remote||invite){persist();remote=null;invite=null;inviteToken=null;inviteLink='';draft=clone(localDraft);history=[];redo=[];view='studio';tab='scene';persist();}
 }catch(err){if(generation!==routeGeneration)return;openModal(`<div class="modal-kicker">YOUR PRIVATE DRAFT IS SAFE</div><h2>这一刻，暂时没能打开。</h2><p class="modal-intro">${e(err.message)}</p><p class="note">你的个人分身和本机草稿还在。邀请关闭或过期时，可以请对方重新邀请。</p><div class="modal-actions">${button('cancel-route','回私密草稿','secondary')}${button('retry-route','重新连接','primary')}</div>`);
 }finally{if(generation===routeGeneration){routeLoading=false;render();}}
}
async function probe(){try{const r=await request('/health',{signal:AbortSignal.timeout(4000)});connected=r.ok===true;}catch{connected=false;}render();}
let rangeBefore=null,fieldBefore=null;
document.addEventListener('focusin',ev=>{if(['title','caption','response'].includes(ev.target.id))fieldBefore=clone(draft);});
document.addEventListener('focusout',ev=>{if(['title','caption','response'].includes(ev.target.id)&&fieldBefore){if(JSON.stringify(fieldBefore)!==JSON.stringify(draft)){history.push(fieldBefore);redo=[];}fieldBefore=null;}});
document.addEventListener('input',ev=>{if(busy)return;const t=ev.target;if(t.id==='avatar-name'){avatarDraft.name=t.value;return;}if(['scale','rotation','position-y'].includes(t.id)){rangeBefore??=clone(draft);const key={'position-y':'y'}[t.id]||t.id;draft.transform[key]=Number(t.value);const person=$('[data-person="me"]');if(person){person.style.top=draft.transform.y+'%';person.style.width=32*draft.transform.scale+'%';person.style.transform=`translate(-50%,-100%) rotate(${draft.transform.rotation}deg)`;updateVisual();}const out=t.previousElementSibling?.querySelector('output');if(out)out.value=t.id==='rotation'?`${t.value}°`:t.id==='scale'?`${Math.round(t.value*100)}%`:`${t.value}%`;return;}if(['title','caption','response'].includes(t.id)){draft[t.id]=t.value;persist();if(t.id==='caption')$('.scene-caption strong').textContent=t.value;if(t.id==='title')$('.canvas-tab').innerHTML=`${ic('photo')} ${e(t.value)}`;}});
document.addEventListener('change',ev=>{const t=ev.target;if(['scale','rotation','position-y'].includes(t.id)){if(rangeBefore){history.push(rangeBefore);redo=[];rangeBefore=null;}persist();render();}if(t.id==='join-consent'){draft.joinConsent=t.checked;persist();}if(t.id==='share-consent')withBusy(()=>consent(t.checked));if(t.id==='photo-input')withBusy(async()=>{const f=t.files?.[0];if(!f)return;if(f.size>15*1024*1024)throw Error('请选择 15 MB 以内的照片');if(!['image/jpeg','image/png','image/webp'].includes(f.type))throw Error('支持 JPG、PNG 和 WebP 图片');let bitmap;try{bitmap=await createImageBitmap(f);}catch{throw Error('这张图片没能打开，试试另一张 JPG 或 PNG');}const factor=Math.min(1,1280/Math.max(bitmap.width,bitmap.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(bitmap.width*factor));c.height=Math.max(1,Math.round(bitmap.height*factor));const ctx=c.getContext('2d');ctx.fillStyle='#eee8df';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(bitmap,0,0,c.width,c.height);bitmap.close();let quality=.84,url=c.toDataURL('image/jpeg',quality);while(url.length>380000&&quality>.35){quality-=.1;url=c.toDataURL('image/jpeg',quality);}if(url.length>400000)throw Error('图片仍然太大，试试更小的照片');commit(d=>{d.scene={kind:'photo',dataUrl:url};});toast('照片已在本机处理，元数据不会保留');});});
document.addEventListener('click',ev=>{const b=ev.target.closest('[data-action]');if(!b||b.disabled)return;const action=b.dataset.action,value=b.dataset.value;if((busy||routeLoading)&&!['close-modal','cancel-route'].includes(action))return;
 const actions={
 'cancel-route':()=>{closeModal();routeGeneration++;routeLoading=false;remote=null;invite=null;draft=clone(localDraft);historyReplace('');persist();render();},'retry-route':()=>{closeModal();withBusy(openRoute);},'return-draft':()=>{routeGeneration++;routeLoading=false;remote=null;invite=null;draft=clone(localDraft);history=[];redo=[];historyReplace('');persist();render();},'studio':()=>{view='studio';render();},'works':()=>{view='works';render();},'new':()=>{closeModal();newWork();},'tab':()=>{tab=value;render();},'avatar':avatarDialog,'close-modal':closeModal,'music':musicDialog,'about':aboutDialog,
 'scene':()=>commit(d=>{d.scene={kind:'builtin',id:value};d.songId=scenes.find(s=>s.id===value).song;stopMusic();playing=false;}),
 'pose':()=>commit(d=>d.avatar.pose=value),
 'undo':()=>{if(!history.length)return;redo.push(clone(draft));draft=history.pop();persist();render();},
 'redo':()=>{if(!redo.length)return;history.push(clone(draft));draft=redo.pop();persist();render();},
 'reset-position':()=>commit(d=>d.transform={x:isGuest()?66:37,y:81,scale:1,rotation:0}),
 'avatar-category':()=>{const n=$('#avatar-name');if(n)avatarDraft.name=n.value;avatarCategory=value;renderAvatarDialog(true);},'avatar-template':()=>{const n=$('#avatar-name');if(n)avatarDraft.name=n.value;avatarDraft.avatar=applyLookPreset(avatarDraft.avatar,TEMPLATES[Number(value)].avatar);renderAvatarDialog();},'avatar-option':()=>{const n=$('#avatar-name');if(n)avatarDraft.name=n.value;avatarDraft.avatar=withAvatarPart(avatarDraft.avatar,b.dataset.key,['accessory','expression','pose'].includes(b.dataset.key)?value:Number(value));renderAvatarDialog();},
 'save-avatar':()=>withBusy(async()=>{avatarDraft.name=$('#avatar-name').value.trim();if(!avatarDraft.name){$('#avatar-name').focus();throw Error('给你的分身起个名字吧');}profile={name:avatarDraft.name,avatar:safeAvatar(avatarDraft.avatar)};commit(d=>{d.avatar=clone(profile.avatar);});closeModal();if(session)await syncProfile();toast('以后每次相遇，都认得出你');}),
 'choose-song':()=>{commit(d=>d.songId=value);stopMusic();playing=false;closeModal();withBusy(async()=>{await playMusic(song(),()=>{playing=false;render();});playing=true;render();});},
 'play':()=>withBusy(async()=>{if(playing){stopMusic();playing=false;}else{await playMusic(song(),()=>{playing=false;render();});playing=true;}render();}),
 'invite':createInvitation,'confirm-invite':()=>withBusy(confirmInvitation),'join':()=>withBusy(joinInvitation),'save':()=>withBusy(saveLocal),'update-remote':()=>withBusy(updateRemote),'save-local-copy':()=>{rememberRemote(remote);toast('已收进我的作品');render();},'discard-shared':()=>{remoteDraft(remote);closeModal();render();},'save-shared-modal':()=>withBusy(async()=>{await updateRemote();closeModal();}),
 'copy-link':()=>withBusy(async()=>{try{await navigator.clipboard.writeText(inviteLink);toast('邀请链接已复制');}catch{$('#invite-link')?.select();toast('请复制已选中的邀请链接');}}),
 'copy-invite':()=>{if(inviteLink){inviteDialog();return;}openModal(`<h2>生成新的邀请链接？</h2><p class="modal-intro">原先的邀请链接会失效。新链接只展示这张作品，不会公开其它草稿。</p><div class="modal-actions">${button('close-modal','暂时不用','secondary')}${button('regenerate-invite','生成新链接','primary')}</div>`);},'regenerate-invite':()=>withBusy(async()=>{const generation=routeGeneration,id=remote.id;const r=await request(`/compositions/${id}/invite`,{method:'POST',token:session.token,body:{revision:remote.revision}});inviteLinks[id]=`${location.href.split('#')[0]}#invite=${encodeURIComponent(r.inviteToken)}`;if(!onWorkRoute(generation,id)){persist();return;}remote=r.composition;inviteToken=r.inviteToken;inviteLink=inviteLinks[id];persist();inviteDialog();}),
 'refresh':()=>withBusy(async()=>{await refreshRemote(true);toast('已更新共同作品状态');}),
 'accept':()=>withBusy(()=>decision(true)),'reject':()=>withBusy(()=>decision(false)),
 'revoke':()=>openModal(`<h2>关闭这次邀请？</h2><p class="modal-intro">链接将不再允许预览或加入。已经入镜的朋友仍能查看共同作品。</p><div class="modal-actions">${button('close-modal','保留邀请','secondary')}${button('confirm-revoke','关闭邀请入口','primary')}</div>`),
 'confirm-revoke':()=>withBusy(async()=>{const generation=routeGeneration,id=remote.id;const {composition:c}=await request(`/compositions/${id}/invite`,{method:'DELETE',token:session.token,body:{revision:remote.revision}});delete inviteLinks[id];if(!onWorkRoute(generation,id)){persist();return;}remote=c;inviteLink='';persist();closeModal();render();toast('邀请入口已关闭');}),
 'leave':()=>openModal(`<h2>从这张作品退出？</h2><p class="modal-intro">你的分身和回应会从共同作品撤下，邀请关闭。已下载的图片无法远程撤回。</p><div class="modal-actions">${button('close-modal','留下','secondary')}${button('confirm-leave','确认退出','primary')}</div>`),
 'confirm-leave':()=>withBusy(async()=>{const generation=routeGeneration,id=remote.id;await request(`/compositions/${id}/participation`,{method:'DELETE',token:session.token,body:{revision:remote.revision}});works=works.filter(w=>w.id!==id);delete pendingEdits[id];if(!onWorkRoute(generation,id)){persist();return;}closeModal();newWork();toast('已退出，个人分身仍然保留');}),
 'export-joint':()=>withBusy(()=>makeExport(true)),'export-solo':()=>withBusy(()=>makeExport(false)),
 'preview':()=>withBusy(async()=>{let markup=$('#artboard').outerHTML;if(toon&&!toonFailed){await toon.ready;const frame=toon.capture({width:960,height:1280}),copy=$('#artboard').cloneNode(true);copy.querySelector('.toon-layer')?.remove();copy.querySelectorAll('.person').forEach(n=>n.remove());copy.classList.remove('toon-ready');const bg=copy.querySelector('.scene-bg');bg.style.backgroundImage=`url("${frame}")`;bg.style.opacity='1';markup=copy.outerHTML;}openModal(`<div class="large-preview">${markup}</div><p class="modal-fine">${remote?'共同作品的保存需要双方确认':'这只是预览，不会上传或公开'}</p>`,'preview-modal');}),
 'open-work':()=>withBusy(async()=>{const w=works.find(w=>w.id===value);if(!w)return;if(w.remoteId){historyReplace(`#work=${w.remoteId}`);await openRoute();}else{draft=clone(w);remote=null;invite=null;history=[];redo=[];view='studio';historyReplace('');persist();render();}}),
 'delete-work':()=>openModal(`<h2>移除这份本机收藏？</h2><p class="modal-intro">只移除当前浏览器的记录，不影响对方的作品或已下载图片。</p><div class="modal-actions">${button('close-modal','保留','secondary')}${button('confirm-delete','移除收藏','primary',`data-value="${e(value)}"`)}</div>`),
 'confirm-delete':()=>{works=works.filter(w=>w.id!==value);persist();closeModal();render();toast('已从本机收藏移除');},
 'reset-session':()=>{session=null;localStorage.removeItem(SESSION_KEY);persist();closeModal();toast('草稿已保留，下次邀请会建立新的身份');}
 };actions[action]?.();
});
window.addEventListener('online',()=>{network=false;probe();});window.addEventListener('offline',()=>{network=true;render();});window.addEventListener('hashchange',openRoute);document.addEventListener('visibilitychange',()=>{if(document.hidden){stopMusic();playing=false;updateVisual();}else render();});
window.addEventListener('pagehide',()=>{stopMusic();persist();toon?.dispose();toon=null;toonLayer=null;});
// AVATAR_BOOTSTRAP
if(!location.hash&&saved.activeWork&&session)historyReplace(`#work=${saved.activeWork}`);routeLoading=location.hash.startsWith('#work=')||location.hash.startsWith('#invite=');render();probe().then(openRoute);
pollTimer=setInterval(async()=>{if(!remote||!session||busy||document.hidden||modal.open||['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)||$('[data-person="me"].dragging'))return;try{const id=remote.id,generation=routeGeneration;const {composition:c}=await request(`/compositions/${id}`,{token:session.token});if(generation!==routeGeneration||remote?.id!==id)return;if(c.revision!==remote.revision){const dirty=isDirty();remoteDraft(c,dirty);await loadPhoto(c.scene,session.token,c.contentRevision);rememberRemote(c);render();toast(c.guest?'共同作品有新的回应':'邀请状态已更新');}}catch{}},5000);
