#!/usr/bin/env python3
"""Export the deliverables from out/*.wav (float) and verify them with ffmpeg's own EBU R128 meter.
usage: export.py  (paths fixed to /tmp/space-video-doodle/music-original)"""
import hashlib, json, os, re, subprocess, sys
import numpy as np
from scipy.io import wavfile

ROOT = '/tmp/space-video-doodle/music-original'
OUT = f'{ROOT}/out'
FF = '/opt/homebrew/bin/ffmpeg'
FP = '/opt/homebrew/bin/ffprobe'
NAME = 'space-doodle-score_124bpm'
PREVIEW = (127.7419, 30.0)          # BREAK -> LIFT (bars 67-82)
os.makedirs(f'{ROOT}/stems', exist_ok=True)
os.makedirs(f'{ROOT}/preview', exist_ok=True)
os.makedirs(f'{ROOT}/png', exist_ok=True)


def run(args):
    r = subprocess.run(args, capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stderr[-2000:])
        raise SystemExit(r.returncode)
    return r


def r128(path):
    r = subprocess.run([FF, '-hide_banner', '-nostats', '-i', path, '-af', 'ebur128=peak=true', '-f', 'null', '-'], capture_output=True, text=True)
    t = r.stderr
    I = float(re.search(r'Integrated loudness:\s+I:\s+(-?[\d.]+) LUFS', t).group(1))
    L = float(re.search(r'Loudness range:\s+LRA:\s+([\d.]+) LU', t).group(1))
    P = float(re.search(r'True peak:\s+Peak:\s+(-?[\d.]+|-inf) dBFS', t).group(1))
    return I, L, P


def probe(path):
    r = run([FP, '-v', 'error', '-show_entries', 'stream=codec_name,sample_rate,channels,bits_per_raw_sample,bits_per_sample,bit_rate:format=duration', '-of', 'json', path])
    return json.loads(r.stdout)


def sha(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(1 << 20), b''):
            h.update(chunk)
    return h.hexdigest()


files = {}
# ---------------------------------------------------------------- master
wav = f'{ROOT}/{NAME}_48k24.wav'
m4a = f'{ROOT}/{NAME}.m4a'
run([FF, '-y', '-v', 'error', '-i', f'{OUT}/master_float.wav', '-c:a', 'pcm_s24le', '-ar', '48000', '-metadata', 'title=Same Moment, Other Side (Music Space doodle score)', '-metadata', 'artist=Music Space team (original, code-synthesised, no samples)', '-metadata', 'comment=124 BPM; generated by src/score.py; see PROVENANCE.txt', wav])
run([FF, '-y', '-v', 'error', '-i', wav, '-c:a', 'aac_at', '-b:a', '256k', '-movflags', '+faststart', '-metadata', 'title=Same Moment, Other Side (Music Space doodle score)', '-metadata', 'artist=Music Space team (original, code-synthesised, no samples)', '-metadata', 'comment=124 BPM; generated by src/score.py; see PROVENANCE.txt', m4a])
files['master_wav'] = wav
files['master_m4a'] = m4a

# ---------------------------------------------------------------- stems
for f in sorted(os.listdir(f'{OUT}/stems')):
    if f.endswith('_float.wav'):
        nm = f.replace('_float.wav', '')
        dst = f'{ROOT}/stems/{nm}_48k24.wav'
        run([FF, '-y', '-v', 'error', '-i', f'{OUT}/stems/{f}', '-c:a', 'pcm_s24le', dst])
        files[f'stem_{nm}'] = dst

# ---------------------------------------------------------------- preview (excerpt at master gain, short fades)
pw = f'{ROOT}/preview/{NAME}_preview-30s_break-lift_48k24.wav'
pm = f'{ROOT}/preview/{NAME}_preview-30s_break-lift.m4a'
st, du = PREVIEW
run([FF, '-y', '-v', 'error', '-ss', f'{st:.4f}', '-t', f'{du:.4f}', '-i', wav, '-af', f'afade=t=in:st=0:d=0.01,afade=t=out:st={du - 2.2:.3f}:d=2.2', '-c:a', 'pcm_s24le', pw])
run([FF, '-y', '-v', 'error', '-i', pw, '-c:a', 'aac_at', '-b:a', '256k', '-movflags', '+faststart', pm])
files['preview_wav'] = pw
files['preview_m4a'] = pm

# ---------------------------------------------------------------- PNGs (plain ffmpeg renders; the annotated map is made by map.mjs)
run([FF, '-y', '-v', 'error', '-i', wav, '-lavfi', 'showspectrumpic=s=2400x900:legend=1:fscale=log:scale=log:start=30:stop=20000:color=intensity', f'{ROOT}/png/spectrogram.png'])
run([FF, '-y', '-v', 'error', '-i', wav, '-lavfi', 'showspectrumpic=s=2400x500:legend=0:fscale=log:scale=log:start=30:stop=20000:color=intensity', f'{ROOT}/analysis/_spec_strip.png'])
run([FF, '-y', '-v', 'error', '-i', wav, '-lavfi', 'showwavespic=s=2400x400:split_channels=1:colors=0x1c1b1a|0xff5c8a', f'{ROOT}/png/waveform.png'])

# ---------------------------------------------------------------- waveform + loudness data for the annotated map
sr, x = wavfile.read(f'{OUT}/master_float.wav')
x = x.astype(np.float64)
mono = x.mean(axis=1)
cols = 2000
seg = len(mono) // cols
env = np.abs(mono[:seg * cols]).reshape(cols, seg)
wave = dict(peak=np.round(env.max(axis=1), 4).tolist(), rms=np.round(np.sqrt((env ** 2).mean(axis=1)), 4).tolist(), seconds=len(mono) / sr)
rep = json.load(open(f'{ROOT}/analysis/report.json'))
json.dump(dict(wave=wave, bar_lufs=rep['bar_lufs']), open(f'{ROOT}/analysis/_mapdata.json', 'w'))

# ---------------------------------------------------------------- verify with ffmpeg
ver = {}
for k, p in files.items():
    I, L, P = r128(p)
    pr = probe(p)
    s = pr['streams'][0]
    ver[k] = dict(path=p, bytes=os.path.getsize(p), sha256=sha(p), duration_s=round(float(pr['format']['duration']), 3), codec=s.get('codec_name'),
                  sample_rate=int(s.get('sample_rate')), channels=s.get('channels'), bits=s.get('bits_per_raw_sample') or s.get('bits_per_sample'),
                  bit_rate=s.get('bit_rate'), lufs=I, lra=L, true_peak_dbtp=P)
    print(f"{k:14s} {os.path.basename(p):58s} {ver[k]['duration_s']:8.3f}s {s.get('codec_name'):10s} {s.get('sample_rate')}Hz bits={ver[k]['bits']}  I={I:6.1f} LUFS  LRA={L:4.1f}  TP={P:6.1f} dBTP  {ver[k]['bytes'] / 1e6:6.1f} MB")
json.dump(ver, open(f'{ROOT}/analysis/deliverables.json', 'w'), indent=1)

# ---------------------------------------------------------------- beats.json at top level (+ measured section loudness)
beats = json.load(open(f'{OUT}/beats.json'))
sec_l = {r['name']: r['lufs'] for r in rep['sections']}
for s_ in beats['sections']:
    s_['measured_lufs'] = sec_l.get(s_['name'])
beats['bar_lufs_measured'] = rep['bar_lufs']
beats['files'] = {k: os.path.relpath(v['path'], ROOT) for k, v in ver.items()}
beats['master'] = dict(lufs_integrated=ver['master_wav']['lufs'], true_peak_dbtp=ver['master_wav']['true_peak_dbtp'], lra=ver['master_wav']['lra'],
                       m4a_true_peak_dbtp=ver['master_m4a']['true_peak_dbtp'], note='measured by ffmpeg ebur128 (peak=true) on the delivered files')
beats['usage'] = {
    'sync': 'Use the WAV for editing (sample-exact). The m4a has the usual AAC encoder delay compensated by an edit list; if an editor ignores edit lists the audio is ~21-23 ms late.',
    'grid': 'bar n starts at (n-1) * bar_s; beat k (0-based) at k * beat_s; 16th steps at step16_s. Everything is on this grid from 0.000 s (no pickup).',
    'type_pops': 'snare_s = backbeats (2 and 4) in the grooves, one snare per bar on beat 3 in PAIN; kick_s = every kick; extra_clap_s = extra claps; sticker_pop hits = glock ding-ding cues.',
    'hook_syllables': 'whistle_notes with a "syllable" field: the cold-open hook phrase sings the rhythm of 同-一-刻 | 另-一-面 (8th, 16th, long).',
    'silences': 'two deliberate digital silences: hard_stop (0.60 s, before the title impact) and payoff_gap (0.48 s, before 交换已接受).',
    'retime': 'SCORE_CONFIG json can change section lengths ({"bars": {"PAIN": 8}}), the AI chime bar/beat ({"ai_chime_bar": 4, "ai_chime_beat": 2}); re-render with src/score.py (~1 min) then src/analyze.py and src/export.py.',
}
json.dump(beats, open(f'{ROOT}/beats.json', 'w'), ensure_ascii=False, indent=1)
print('beats.json written;', len(beats['hits']), 'hits,', len(beats['bar_starts_s']), 'bar starts')
